### ISSUE TITLE
Renaming all flavors to organization names

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#102]
metanorma-csd => metanorma-cc
metanorma-rsd => metanorma-ribose
metanorma-vsd => metanorma-vg
metanorma-mpfd => metanorma-mpfa
metanorma-m3d => metanorma-m3aawg

mn-samples-mpf => mn-samples-mpfa
mn-templates-csd => mn-templates-cc

**Comment by opoudjis** [comment]
@CAMOBAP, I am doing this renaming. Apparently you need to update CIMAS? Ronald is redirecting the repositories, if that helps.

**Comment by CAMOBAP** [comment]
Yep, I will update, @opoudjis just let me know once it done

**Comment by opoudjis** [comment]
Alex, you may now proceed, though gem release will not happen till tomorrow
