### ISSUE TITLE
metanorma GHA not working

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#106]
Javascript complaining between latest checking and this; Javascript has not been changed.

https://github.com/metanorma/metanorma/runs/595134601

**Comment by CAMOBAP795** [comment]
May be related to https://github.com/puppeteer/puppeteer/releases/tag/v3.0.0 release

And specifically Node.js v8.x.x is no longer supported. (#5136) checking

**Comment by CAMOBAP795** [comment]
PR is ready waiting for approval once it will be done I will propagate changes to all repos https://github.com/metanorma/metanorma/pull/107

**Comment by CAMOBAP795** [comment]
Fixed in configuration https://github.com/metanorma/metanorma-build-scripts/commit/8bea78aef90f275786faff153c421c4ab2bc22e2
