### ISSUE TITLE
Add font list for every flavor gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#108]
List of all flavors:

CSA:
AzoSans, AzoSans-Light, SourceCodePro-Light

CalConnect:
SourceSansPro, SourceSerifPro, SourceCodePro, HanSans

IEC:
Arial, Times New Roman, HanSans, Courier

ISO:
Cambria, Times New Roman, Cambria Math, HanSans, Courier

ITU:
Arial, Courier, Times New Roman

OGC:
Arial, Courier, Times New Roman

Ribose:
SourceSansPro-Light, SourceSerifPro, SourceCodePro-Light, HanSans

UN:
Arial, Arial Black, Courier, Times New Roman, HanSans

We can put them in such a structure:

```ruby
module Metanorma
  module Csa
    def self.fonts_used
      %w[AzoSans AzoSans-Light SourceCodePro-Light]
  end
end
```

(These fonts come from a grep from mn-native-pdf, and are slightly forward looking)

**Comment by ronaldtse** [comment]
FYI @Intelligent2013

**Comment by opoudjis** [comment]
This is specific to PDF, so it's being called self.pdf_fonts

**Comment by ronaldtse** [comment]
@opoudjis why are we using `self.pdf_fonts`? Both PDF and Word should use the same fonts??

**Comment by ronaldtse** [comment]
In fact, PDF, Word and HTML should be using the same fonts.

**Comment by ronaldtse** [comment]
Closing in favor of #114 .

**Comment by opoudjis** [comment]
> @opoudjis why are we using `self.pdf_fonts`? Both PDF and Word should use the same fonts??

> In fact, PDF, Word and HTML should be using the same fonts.

(a) They aren't, (b) There is no reason why they should. And you have never asked that I change the HTML or Word fonts to match these. Need to discuss.

**Comment by opoudjis** [comment]
Carry across these fonts to HTML and DOC output
