### ISSUE TITLE
Remove `sassc` from gem runtime dependency

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#109]
`sassc` is only used for generation of stylesheets that are used in flavor gems.

Typically, stylesheets are not customizable by users (there is an exception).

In order to install `sassc`, the user's computer needs to compile `sassc` and its toolchain, which is complex and unnecessary.

We would like to pre-compile the `.sass` templates (with plugins) as part of the gem release process (add it in the Rakefile for `rake release`).

Right now the `.sass` files include liquid template syntax; in order to keep the liquid code there we will need to comment them in SASS syntax prior to passing the `.sass` files to the `sass` command. 

i.e.
```
{% foreach item in data %}
body {
  font: 100% Helvetica, sans-serif;
  color: #333; }
{% endfor %}
```

=>
```
/* {% foreach item in data %} */
body {
  font: 100% Helvetica, sans-serif;
  color: #333; }
/* {% endfor %} */
```

This should also speed up the processing flow when the user generates the documents as the stylesheets are pre-compiled. We will need to do some profiling to know whether this is of great effect.

**Comment by ronaldtse** [comment]
Once we have this we can get rid of the `sassc` fork!

**Comment by w00lf** [comment]
@ronaldtse @opoudjis i have thought a little bit about how to implement this seamlessly. We cant hook up this into metanorma build itself as sassc files are actually located in flavor gem, not in metanorma itself. The only way i can think of is to create custom rake release in isodoc gem to compile sassc during release build, after that, we need to require this task in all our flavor gems. After that we can safely remove sassc from runtime dependency.

**Comment by ronaldtse** [comment]
@w00lf indeed, can you please help proceed as described? As long as the SASS => CSS process does not break the liquid code, it's good. Thanks.

**Comment by w00lf** [comment]
> @w00lf indeed, can you please help proceed as described? As long as the SASS => CSS process does not break the liquid code, it's good. Thanks.

Sure, I will start with isodoc then, will create new rake task there

**Comment by ronaldtse** [comment]
@w00lf are we done soon? Thanks.

**Comment by w00lf** [comment]
> @w00lf are we done soon? Thanks.

i have done isodoc gem refactoring, tested on metanorma-m3aawg flavor new gem build. Now I need to test and duplicate changes into other flavors
