### ISSUE TITLE
Supporting a "document collection"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#110]
A Metanorma document collection (MNDC) is a collection of Metanorma documents.

This is an extension of the simple Relaton collection we have today. 

There are two examples in Metanorma:
* MPFD documents are arranged in a collection -- each document can be published independently yet also within a collection.
* The ISO 10303 SMRL is a "document collection" in which it contains hundreds of standards within a mini-site.

Requirements:

* Cross-references
  * A document can refer to any document element within another document in the same document collection. Any broken references should be detected by the compilation process.

* Collection-specific features
  * organization of documents - what is the hierarchy?
  * support of collections inside collections (e.g. series > vol > doc)
  * e.g. collection-wide glossary, index, tables, figures?

* Metadata
  * There are metadata data elements that apply to the document collection, mainly like bibdata but also probably special attributes that apply to collections.
  * Each document can exist/be published as a separate document and have its own metadata

* Storage
  * Metanorma should have an option of generating a single XML file for the whole collection.
  * Metanorma may have an option of using a single manifest (collection XML file) + multiple XML files (one per MN document) to represent the whole collection.

* Rendering
  * There is an option to generate a mini-site from a MN document collection (HTML)
  * Every document can be published as whatever output formats supported, e.g. Word, PDF.

**Comment by opoudjis** [comment]
Writing up spec in https://github.com/metanorma/metanorma/wiki/Metanorma-collections

**Comment by opoudjis** [comment]
Test instance of YAML to Metanorma Collection published to https://github.com/metanorma/metanorma/tree/master/spec/examples/metanorma-collection

**Comment by opoudjis** [comment]
I am closing the ticket with the prototype version linked above. The scripts will need to be migrated into a gem, but the basic functionality is now in place.
