### ISSUE TITLE
Introduce titles for items - contents, tables, etc.

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#118]
Introduce a dictionary (into XML) for item's titles such 'Table of contents', 'Table', 'Figure', etc. to render a PDF documents on different languages (on French, for example)

Here is static texts from XSLT for English documents:
- ANNEXES
- Annex
- Appendix
- Approval Date
- Box
- Category
- Change
- Clause
- Contents
- DEPRECATED
- Date
- Document language
- Document stage
- Document type
- EXAMPLE
- Edition
- Editor
- External identifier of this OGC® document (for OGC)
- Figure
- Formula
- IMPORTANT
- Internal reference number of this OGC® document (for OGC)
- Key
- Keywords
- List of Figures
- List of Tables
- Month names - January, February, ...
- NOTE
- Note x to entry
- 'No.'
- Ordinal numbers - for example 'second', 'seventh', 'thirteenth'.
- Page
- Pages
- Part
- Publication Date
- Recommendation
- Reference number
- SOURCE
- Secretariat
- Section
- Submission Date
- Submitting Organizations
- Table
- Type
- Version
- Voting begins on
- Voting terminates on
- modified
- where

from @ronaldtse  (https://github.com/metanorma/mn-native-pdf/issues/110#issuecomment-626304752)
> I think those keys have to be provided in the XML as a dictionary, because for later rendering we won’t be able to reproduce the same text depending on implementation

**Comment by opoudjis** [comment]
I have a "dictionary" of a lot of these for internationalisation, as you can see in https://github.com/metanorma/isodoc/tree/master/lib/isodoc-yaml (with flavour-specific expansions). I have repeatedly offered to export these to you as variables, but I guess I have to do things this way.

I am not agreeing to translate every single snippet of static text into what you are requesting. The "dictionary" is driven by internationalisation; OGC, for example, is monolingual.

**Comment by ronaldtse** [comment]
> I am not agreeing to translate every single snippet of static text into what you are requesting. The "dictionary" is driven by internationalisation; OGC, for example, is monolingual.

OGC has stated its wish to be multilingual, they have a number of documents translated to Chinese.

**Comment by opoudjis** [comment]
Internationalisation is now done in the XML, so this ticket is no longer needed.
