### ISSUE TITLE
Test Ruby 2.7.0

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#120]
Some components of Metanorma are failing under Ruby 2.7.0 which is released. We need to fix all components.

**Comment by ronaldtse** [comment]
In particular, the `cnccs` gem has issues as Ruby 2.7.0 has changed the `CSV` class interface.

**Comment by CAMOBAP** [comment]
@ronaldtse two more questions:
 - Should we still test on 2.4
 - Should we allow failure for Ruby 2.7?

**Comment by ronaldtse** [comment]
> Should we still test on 2.4

Yes.

> Should we allow failure for Ruby 2.7?

Yes. 

Thanks!

**Comment by CAMOBAP** [comment]
1.
Observed issues Windows
 - ```
   Gem::RuntimeRequirementNotMetError: nokogiri requires Ruby version >= 2.3, <
   2.7.dev. The current ruby version is 2.7.1.83.
   ```

2. csv api changes
https://github.com/metanorma/metanorma-itu/issues/205

3. problems with installation last chocolatey package https://github.com/metanorma/chocolatey-metanorma/issues/46

**Comment by CAMOBAP** [comment]
@ronaldtse for the first problem as far as I understood we need to wait for next stable version of nokogiri, and it's already fixed in https://github.com/sparklemotion/nokogiri/issues/1961#issuecomment-585860989

Technically this task is ready

**Comment by ronaldtse** [comment]
@CAMOBAP let's move on with it, thanks!

**Comment by CAMOBAP** [comment]
hmm, my bad PR wasn't prepared by cimas for some reason, now changes pushed
