### ISSUE TITLE
Support `express_ref:[]` syntax (TBD)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#122]
See https://github.com/metanorma/annotated-express/

**Comment by opoudjis** [comment]
Required by https://github.com/metanorma/annotated-express/issues/12

**Comment by opoudjis** [comment]
On hold pending lutaml extracting remarks and schema code.

**Comment by opoudjis** [comment]
This is very difficult. 

The lutaml plugin reads in a single schema in isolation, and processes it in a Liquid template. The anchors are not generated (currently) by the lutaml plugin, but by Metanorma liquid templates:

````
{% for entity in schema.entities %}
[[{{schema.id}}.{{entity.id}}]]
==== {{ entity.id }}
````

Cross-references can be between any two schemas, and the only agent assigning asciidoctor identifiers to those references is Metanorma. Cross-references may well be between documents, with each document presenting a separate subset of schemas; so they will only be resolved in the final case in a document collection. 

The text of the crossreference is the label content, or rather the final component thereof (`action_schema.action_relationship.relating_action` is rendered as `relating_action`; `action_request_solution.wr:WR1` is rendered as `WR1`).

There is no oracle of identifiers currently, and no oracle external to Metanorma will know what document a particular schema has ended up in.

So to deal with these, we will process express_ref:[] as `eref`: external references, and we will progressively resolve them.

* Each express_ref:[] reference starts with a schema identifier. We will gather each schema identifier, and make it a hidden external cross-reference. So `express_ref:[A.B.C]` => `<eref bibitem="A"><location type="anchor">B.C</location>C</eref>`, and we will insert `<references hidden="true">` at the end of each document containing express_ref, with a `<bibitem id="A"><docidentifier type='repository'>express/A</docidentifier></bibitem>` for each A.
* If we have inserted in the current document via lutaml a reference to schema A (which crudely we will recognise through `//*[id = 'A']`, though we may want to disambiguate express identifiers by prefixing), then we will resolve all `<eref bibitem="A"><location type="anchor">B.C</location>C</eref>` into `<xref target="A.B.C">C</xref>`
* If any express_ref:[] references are unresolved in a single document, they are to be resolved in a collection, in a similar way to how cross-references between documents are resolved in collections. We will need to do two passes: 
  * First, register all express schema identifiers in the collection against their file. (That prefixing will be needed, it looks like, to identify express schema invocations explicitly.)
  * Then, for each file, for each unresolved express bibitem referenced, replace A in `<eref bibitem="A"><location type="anchor">B.C</location>C</eref>` with a file reference F, as `<eref bibitem="F"><location type="anchor">A.B.C</location>C</eref>`
  * If any entries are unresolved, at least the reference is intelligible (and we may need to unhide the schema reference): `<eref bibitem="A"><location type="anchor">B.C</location>C</eref>` => `unresolved identifier B.C in schema A`.

**Comment by opoudjis** [comment]
Eventually, we will supplant `express_ref:[A.B.C]` by `<<express:A:B.C,C>>`.

**Comment by opoudjis** [comment]
To start: we need to allow user setting of the type of a clause in standoc, so that we can generate `<clause id="A" type="express-schema">`.

**Comment by opoudjis** [comment]
If an internal crossreference cannot be resolved in metanorma (that is, the document ID it is pointing to does not exist), do not abort execution, but generate error string within document, as well as warnings.

**Comment by opoudjis** [comment]
Will also want to generate log file for such errors.

**Comment by opoudjis** [comment]
Moving express_ref:[] to standoc, and then genericising it to colon-delimited xrefs.

**Comment by opoudjis** [comment]
Will not prefix the container id to the anchor id: they are decoupled.

**Comment by opoudjis** [comment]
documentation of clause  types lost; resubmitted
