### ISSUE TITLE
Support `import_express_schema:[]` (TBD)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#123]
TBD

See https://github.com/metanorma/annotated-express/blob/master/data/documents/resources/fundamentals_of_product_description_and_support/sections/04-schemas.adoc

```
import_express_schema::../resources/action_schema/action_schema.exp[]
or
include::../resources/action_schema/action_schema.exp[source=express]
```

This requires integration with Express Engine https://sourceforge.net/projects/exp-engine/

**Comment by opoudjis** [comment]
Has apparently been implemented, need to know how.

**Comment by opoudjis** [comment]
Needed for https://github.com/metanorma/annotated-express/issues/12

**Comment by opoudjis** [comment]
This hasn't been fully implemented, but will be once expressir exposes both remarks and source code to lutaml.

**Comment by opoudjis** [comment]
The paths in the asciidoctor extracted by lutaml from express need to be updated to reflect the calling environment. So:

`[lutaml, ../../../resources/action_schema/action_schema.exp, repo]`

is fetching a line containing:

`image::action_schemaexpg1.xml`

Something needs to update that URL from action_schemaexpg1.xml to ../../../resources/action_schema/action_schemaexpg1.xml

Am considering whether that is me or you...

**Comment by opoudjis** [comment]
This has been implemented, and any fixes are going to be new tickets.
