### ISSUE TITLE
Implement metanorma collections code

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#126]
In #110, I have created two scripts to convert a YAML file into a Metanorma collection:

The files and test data are in https://github.com/metanorma/metanorma/tree/master/spec/examples/metanorma-collection

https://github.com/metanorma/metanorma/wiki/Metanorma-collections gives the grammar of the Metanorma collection specification

* `make.sh` runs the collection generation
* `ruby yaml2xml.collection.rb collection1.yml > collection1.xml` converts the YAML collection specification into the target Metanorma XML format
* `ruby collection-render.rb collection1.xml collection_cover.html collection1` generates an HTML rendering of the collection: the anchor HTML page, and the individual document pages it points to. It has three arguments: the Metanorma XML format generated by the preceding script; the HTML Liquid Template to be used for the anchor HTML page, and the destination directory to generate the HTML in

Your task is to migrate the functionality of these two scripts into the metanorma and metanorma-cli gems. To do that, you will need to become familiar with the structure of those gems, and the frameworks they employ.

* metanorma-cli processes the command line commands around metanorma, and invokes code in the metanorma gem to actually do the processing. 

So the code in the two scripts will end up in metanorma: you will likely generate a file parallel to lib/metanorma/compile.rb. It would be desirable for you to use the input/ and output/ modules to modularise out the input and output formats.

The command you are implementing is:

`metanorma collection {input-file} -x {format} -w {output-folder}`

The input-file is either YAML or XML. If YAML, generate the XML output, and keep going. If XML, keep going.

The format, as with `metanorma compile`, is a comma-delimited list of formats: `xml` is the Metanorma XML collection file; pdf, html, doc. 

The output-folder is mandatory; we could just say "output to the input folder", but that's counterproductive.

You will see in yaml2xml.collection.rb the command `system "metanorma compile -x html #{f.path}"` under `files`. If the format is pdf or doc, you generate the pdf or doc file instead (`system "metanorma compile -x doc #{f.path}"`), but you do not generate the anchor page, done in the `coverpage` method.

For now, we will implement the Liquid template as a distinct argument, `-c {coverpage}`, mandatory only if HTML is an output format. We may fold the coverpage into the YAML directives container later on, and make it optional.

**Comment by opoudjis** [comment]
This code will be impacted by https://github.com/metanorma/metanorma-standoc/issues/285 . I will update it once that issue is concluded.

**Comment by opoudjis** [comment]
@w00lf Can now be actioned.

**Comment by w00lf** [comment]
> @w00lf Can now be actioned.

got you!

**Comment by opoudjis** [comment]
@w00lf if you are too busy, I'll assign it to @andrew2net; @ronaldtse wants this done in the next few days.

**Comment by ronaldtse** [comment]
@opoudjis @w00lf is likely too busy. @andrew2net can you help handle this? Thanks!

**Comment by andrew2net** [comment]
> You will see in yaml2xml.collection.rb the command `system "metanorma compile -x html #{f.path}"` under `files`.

@opoudjis I think calling a system command slows down the process. Shall we use direct call metanorma's methods?

**Comment by ronaldtse** [comment]
Absolutely, let’s use direct calls.

**Comment by andrew2net** [comment]
@opoudjis the file `collection1.yml` has references to `dummy.xml` and `rice1-en.final.xml` however, there are only `dummy.adoc` and `rice1-en.final.adoc`. Should the script looks for a file in other formats and attempts to convert it?
