### ISSUE TITLE
Add mn-templates-* testing for all executable deliverables (docker, homebrew, chocolatey, packed-mn)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#133]
We should add templates testing for all executable deliverables (docker, homebrew, chocolatey, packed-mn).

From @camobap

> maybe we should add templates testing with packed-mn

_Originally posted by @ronaldtse in https://github.com/metanorma/packed-mn/issues/52#issuecomment-658548212_

**Comment by CAMOBAP** [comment]
At the moment this looks overkill

For now, we do this testing on metanorma-cli only and do samples testing on other deliverables

If we are going to switch from samples to templates it makes sense to me but add one more test suite probably not
