### ISSUE TITLE
Consolidated build status matrix for deliverables

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#135]
For all auto-triggered builds for new release deliverables, there should be a single location to see the build status:

* https://github.com/metanorma/packed-mn/
* https://github.com/metanorma/homebrew-metanorma/
* https://github.com/metanorma/metanorma-docker/
* https://github.com/metanorma/chocolatey-metanorma/
* https://github.com/metanorma/metanorma-linux-setup (pending https://github.com/metanorma/metanorma-linux-setup/issues/29)
https://github.com/metanorma/metanorma-snap (pending https://github.com/metanorma/metanorma-snap/issues/8)

Right now, the first 3 are failing at master.

**Comment by CAMOBAP** [comment]
Potential implementations:
 - wiki page with paragraphs for each release and tables with build statuses (badges)
 - metanorma-cli->releases details
 - _to be continued..._

@ronaldtse if you have a vision how it should be implemented please let me know

**Comment by ronaldtse** [comment]
I think a Wiki page or a new repo with a dashboard would both work. I don't have a better idea...

**Comment by CAMOBAP** [comment]
@ronaldtse I think this page more or less can be used for described goal https://github.com/metanorma/metanorma-release#metanorma-environments

**Comment by ronaldtse** [comment]
@CAMOBAP agree. Thanks!
