### ISSUE TITLE
Collections need to force all anchors in documents they include to be unique

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#142]
This is most expediently done by namespacing all anchors, prefixing them with the document identifier for the document they are in. That will need to be done in preprocessing, and it will need to be respected in links between documents.

This also applies to footnote anchors.

**Comment by opoudjis** [comment]
To explain this:

There is code in this gem to generate document collections. Part of that code, in collection_renderer.rb, processes the XML of all component documents within the collection, to resolve links between documents within the collection: `file = update_xrefs(file, identifier)`. The preprocessed document is saved to disk, and only those preprocessed documents are concatenated into the collection.

Now, anchor identifiers within a document are required to be unique, but they may be reused between documents. For example, "_introduction" will be used by default by Asciidoctor as the identifier of an "introduction" clause in any document. If those documents get concatenated into a single XML or HTML document,  we have a problem: the identifiers will no longer be unique within the document.

In order to address that problem, before the `update_xrefs()` routine is run, a separate routine needs to be run, prefixing all anchor identifiers within a document with a unique document identifier, to act as a namespace preserving their uniqueness. Note that `identifier` in `files()`, the routine preprocessing each file, is the document identifier used within the collection; so it needs to be prefixed to all anchor identifier instances in the file. Moreover, `update_anchors()` called within `update_xrefs()` needs to be updated: the document anchor `ref_from` in that routine needs to be prefixed with that document's identifier, the same way as crossreferences do within a document.

The attributes impacted by this are:

* (any element)/`@id`
* `review/@from`
* `review/@to`
* `xref/@target`
* `callout/@target`

**Comment by Intelligent2013** [comment]
Additional:
- `eref/@bibitemid`
- `source/@bibitemid`
- `origin/@bibitemid`

**Comment by opoudjis** [comment]
Expand to: `*/@bibitemid` : We've missed `<termdocsource bibitemid="ISO712"/>`
