### ISSUE TITLE
Hiding references and bibitems

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#148]
Follow-on from https://github.com/metanorma/metanorma/issues/146.

Cross-references between documents are realised via bibliographies. This remains the case even if the document is included in a collection. However, if the document is read as a single document (as is the case for the BIPM Brochure), the bibliography should not be rendered. (I do not want to delete it either, in case the erefs point to it need to gather further information.)

For that reason, bibitems in Presentation XML may now be flagged with hidden=true; and if a references element consists of only hidden bibitems, the references element itself may be flagged with hidden=true. If that is the case, the elements so flagged are skipped during rendering.

**Comment by Intelligent2013** [comment]
Done.
