### ISSUE TITLE
GHA: Replace all mn-{samples, templates}-* Makefiles with new metanorma-cli site generation functionality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#151]
This is to replace GHA workflows for all Metanorma document repositories to use the new `metanorma site generate` functionality. 

We can remove:
* Makefile
* Makefile.win
* deploy_key (legacy)

And update the GHA workflows.

**Comment by CAMOBAP** [comment]
Done for all samples, also cimas configuration update for templates too, will be updated soon

**Comment by CAMOBAP** [comment]
Done
