### ISSUE TITLE
Image maps in HTML collections

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#160]
Needed for https://github.com/metanorma/annotated-express/issues/13 and https://github.com/metanorma/annotated-express/issues/15

Need to take as input GIF and image map, and generate SVG with embedded hyperlinks:

* https://vecta.io/blog/the-best-way-to-make-image-maps
* https://html.com/images/how-to-make-an-image-map/

Will need to define image map as an artefact with Metanorma-compatible xrefs and internal erefs. These will be transformed in collection output (and if xref-only within metanorma document) to SVG.

Once I have a target format that works, I will need to request that the source XMLs be converted into it.

**Comment by ronaldtse** [comment]
This is interesting for all model-based standards, because they often have model diagrams.
However, generating the image maps may have to be a separate process.

1. I don't know if there are any good tools to slice image maps.
2. I'm not sure if those diagramming tools can export SVG and allow embedding links

There is a suggestion to use something like draw.io to implement some graphic editor, but I'm not sure how easy it is to get the output we need.

**Comment by ronaldtse** [comment]
We may need to support SVG (and other image formats) input, too. The key point is either we have to create a new SVG, or adjust an existing SVG.

**Comment by opoudjis** [comment]
We have two target formats, HTML image maps and SVG image maps; the source format for ISO 10303 is equivalent to HTML image maps.

I am specifying hot areas in metanorma, and transforming them. Generating them is out of scope of metanorma, and must remain so.

The reference of the hot area can be any of a link, an xref, or an internal eref.

2-D geometry is specified as a shape and a sequence of coordinates or distances.

So 

````
[imagemap,images/image.gif,Workmap]
----
* rectangle; <<ref1,Computer>>; (0, 1); (2, 3)
* circle; http://www.example.com[Phone]; (5, 6); 7
* poly; <<express:action_schema:action_schema.basic,Coffee>>; (8, 9); (10, 11); (12, 13)
----
````

can map to Metanorma XML

````
<imagemap src="images/image.gif" alt="Workplace">

<area type="rect">
<xref target="ref1">Computer</xref>
<coords x="0" y="1"/>
<coords x="2" y="3"/>
</area>

<area type="circle">
<link target="http://www.example.com">Computer</xref>
<coords x="5" y="6"/>
<radius x="7"/>
</area>

<area type="poly">
<eref bibitem="express_action_schema">
<localityStack>
                 <locality type='anchor'><referenceFrom>action_schema.basic</referenceFrom></locality>
</localityStack>
Coffee</eref>
<coords x="8" y="9"/>
<coords x="10" y="11"/>
<coords x="12" y="13"/>
</area>

</imagemap>
````

and maps to HTML image map

````
<img src="images/image.gif" alt="Workplace" usemap="#name1">

<map name="name1">
  <area shape="rect" coords="0,1,2,3" alt="Computer" href="#ref1">
  <area shape="circle" coords="5,6,7" alt="Phone" href="http://www.example.com">
  <area shape="circle" coords="8,9,10,11,12,13" alt="Coffee" href="fundamentals.html#action_schema.basic">
</map>
````

**Comment by ronaldtse** [comment]
Just to clarify we’re going to supersede HTML maps with SVG maps. There is no reason why we need HTML maps which are not even responsive.

**Comment by opoudjis** [comment]
As you have just conceded, we need to allow for them. ISO 10303 are not the only users in the world.

If an SVG is provided to the imagemap, then instead the macro will contain a mapping from a/href values in the SVG to the targets provided by xref, eref and link. So:

````
[svgmap,images/image.svg,Workmap]
----
* <<ref1,Computer>>; href1.htm
* http://www.example.com[Phone]; http://www.example.com
* <<express:action_schema:action_schema.basic,Coffee>>; href2.html#abc
----
````

mapping to Metanorma XML:

````
<svgmap src="images/image.svg" alt="Workplace">

<target href="href1.html">
<xref target="ref1">Computer</xref>
</target>

<target href="http://www.example.com">
<link target="http://www.example.com">Computer</xref>
<target>

<target href="href2.html#abc">
<eref bibitem="express_action_schema">
<localityStack>
                 <locality type='anchor'><referenceFrom>action_schema.basic</referenceFrom></locality>
</localityStack>
Coffee</eref>
</target>

</svgmap>
````

**Comment by opoudjis** [comment]
At Ronald's request, I am complicating the workflow more, in pursuit of DRY.

The image maps can only contain hrefs. The svgmap is used to update the hrefs in the image map with local values.

[imagemap,images/image.gif,Workmap]
----
* rectangle; link:href1.htm[]; (0, 1); (2, 3)
* circle; http://www.example.com[]; (5, 6); 7
* ellipse; http://www.example.com[]; (14, 15); 16; 17
* poly; link:href2.html#abc; (8, 9); (10, 11); (12, 13)
----


[svgmap,images/image.svg,Workmap]
----
* <<ref1,Computer>>; href1.htm
* http://www.example.com[Phone]; http://www.example.com
* <<express:action_schema:action_schema.basic,Coffee>>; href2.html#abc
----

**Comment by opoudjis** [comment]
Sample svgs attached.

[action_schemaexpg1.svg.zip](https://github.com/metanorma/metanorma/files/5866260/action_schemaexpg1.svg.zip)

**Comment by ronaldtse** [comment]
Relevant XML in the SVG file:

```svg
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 595.28 841.89" style="enable-background:new 0 0 595.28 841.89;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#000000;stroke-miterlimit:10;}
</style>
<image style="overflow:visible;" width="368" height="315" xlink:href="data:image/gif;base64,..." transform="matrix(1 0 0 1 114 263.8898)">
</image>
<a xlink:href="mn://action_schema" >
	<rect x="123.28" y="273.93" class="st0" width="88.05" height="41.84"/>
</a>
<a xlink:href="mn://basic_attribute_schema" >
	<rect x="324.69" y="450.52" class="st0" width="132.62" height="40.75"/>
</a>
<a xlink:href="mn://support_resource_schema" >
	<rect x="324.69" y="528.36" class="st0" width="148.16" height="40.75"/>
</a>
</svg>
```

**Comment by opoudjis** [comment]
The images in svgmaps need to be treated the same as images anywhere in Metanorma. So the image shall not given as a src argument to the svgmap macro; instead, it shall be a full image macro, with all its own arguments. And the svgmap in Metanorma XML shall be a wrapper around figure.

Therefore, there is no need for svgmaps to be macros at all: like pseudocode, they shall be examples with an svgmap role or style attribute.
