### ISSUE TITLE
Use new Fontist `--no-progress` option to prevent showing much progress

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#167]
From https://github.com/fontist/fontist/pull/227#event-4443750152

@CAMOBAP can we use this new --no-progress option for Metanorma fontist installs? Thanks.

**Comment by ronaldtse** [comment]
And this was started by @CAMOBAP : https://github.com/fontist/fontist/issues/213

**Comment by CAMOBAP** [comment]
Implemented in the scope of metanorma/metanorma-cli#227
