### ISSUE TITLE
Crossreference other documents in collection at collection processing time

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#198]
In order for references to a document in a collection to be realised as hyperlinks within the collection, we currently require that the document identifier in the document be edited to a repo:() identifier; e.g.

`* [[[iso_std_iso_44001_ed-1_en,repo:(current-metanorma-collection/ISO 44001)]]], _Collaborative business relationship management systems — Requirements and framework_`

That means that independent documents have to be edited before they can be added to a collection. 

It should at least be an option to configure that intervention at the collection level instead, specifically in the collection manifest. That way, documents can be included in a collection unchanged.

**Comment by ronaldtse** [comment]
Thanks for this ticket @opoudjis , very clear on what is needed.
