### ISSUE TITLE
Publish XML tag mapping with STS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#199]
Given the usage of mn2sts and sts2mn, we should publish:

1. A mapping document between Metanorma and ISOSTS/NISO STS
2. Description of how the conversion process works, and any caveats in the process (non-round-trip issues)

This was a mapping done in 2020, we should convert this into something structured and publish it for development purposes.

[MN XML mapping to ISOSTS and NISO STS.docx](https://github.com/metanorma/metanorma/files/6714446/MN.XML.mapping.to.ISOSTS.and.NISO.STS.docx)

**Comment by Intelligent2013** [comment]
I've completely refactored the documentation, uploaded in 'mnconvert' repo: https://github.com/metanorma/mnconvert/raw/master/doc/MN%20XML%20mapping%20to%20ISOSTS%20and%20NISO%20STS.v2.docx

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Let me actually move this issue to metanorma.org. I wonder how we can document this nicely on a website...

**Comment by Intelligent2013** [comment]
> I wonder how we can document this nicely on a website...
@ronaldtse we can use this workflow:
- manually: edit docx in Word -> 'save as' filtered web-page (html)
- automatically on github commit: clean up with 'tidy' -> convert to destination html format, or adoc via simple xslt (remove Word's specific attributes, add metanorma.org's css classes, etc) -> publish to metanorma.org
There is an advantage when we commit html on github - we can track changes, no need to compare two docx in Word to see what is changed.
But it's my theoretical thoughts...

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013!
