### ISSUE TITLE
[fontist] 'Courier' font is not supported.

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma#210]
[fontist] 'Courier' font is not supported. Please report this issue at github.com/metanorma/metanorma/issues to report this issue.

https://github.com/metanorma/packed-mn/runs/3341037657?check_suite_focus=true#step:5:1025

**Comment by alexeymorozov** [comment]
By some reason it used a previous version of metanorma-nist:

`Using metanorma-nist 1.3.9`

But should 1.3.10 which contains the fix.

**Comment by CAMOBAP** [comment]
@alexeymorozov thanks release workflow failed so I just restarted it https://github.com/metanorma/metanorma-nist/actions/runs/1135366286

I will watch for the release

**Comment by alexeymorozov** [comment]
Ok, thanks @CAMOBAP!

**Comment by CAMOBAP** [comment]
Release passed I will restart packed-mn workflows once CI on packed-mn will be less busy

cc @ronaldtse

**Comment by ronaldtse** [comment]
The error message seems to repeat itself? "Please report this issue at github.com/metanorma/metanorma/issues to report this issue."

**Comment by CAMOBAP** [comment]
Already fixed
