### ISSUE TITLE
Supporting parallelisation in processing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#220]
In metanorma/metanorma-iso#544 the XML processing is painfully slow because everything is done in sequential order.

We should be able to break up the XML generation piecemeal, and that means that the "includes" we use should not be "expanded into text" before processing.

We may need to reconsider the manner we consume input and organise data.

(also relevant to metanorma/metanorma-iso#545)

**Comment by opoudjis** [comment]
My finding is that this is not the case at all.

* The main time sink in XML generation is fetching references, and a recent cleanup to move commas inside of tags for proper smart quotes processing, which was implemented through inefficient XPath querying of text.
* Without those two processes, XML generation falls from 80 mins TO TWO. There is zero point in parallelising anything in XML processing, particularly given how much it will derail the document model.

There *is* a point in parallelising the generation of HTML, Word, and PDF: these are sequential jobs, taking 27 min for Word, 18 min for PDF, 16 min for HTML. But that has NOTHING to do with the generation of the initial XML.

**Comment by ronaldtse** [comment]
> The main time sink in XML generation is fetching references, and a recent cleanup to move commas inside of tags for proper smart quotes processing, which was implemented through inefficient XPath querying of text.

If that were the case then a cache would fix this. But it is not true. Try running it again...

**Comment by opoudjis** [comment]
The cache did fix it. It's now 3 minutes, with the quote cleanup optimised. I am running it.

**Comment by andrew2net** [comment]
is the async method [`Relaton::Db#fetch_async`](https://github.com/relaton/relaton#fetch-document-by-references) in this case?

**Comment by opoudjis** [comment]
No, just fetch... there is a fetch async?

**Comment by andrew2net** [comment]
@opoudjis it's described here https://github.com/relaton/relaton#fetch-document-by-references
> - `Relaton::Db#fetch_async(reference, year, options, &block)` - fetches document asynchronously

example:
```
# Fetching asynchronously

# prepare queue for results
results = Queue.new

# references to fetch
refs = ["ISO 19011", "ISO 19115"]

# fetch documents
refs.each do |ref|
  db.fetch_async(ref) do |doc|
    results << [ref, doc]
  end
end

# wait until documents fetching
refs.size.times do
  ref, doc = results.pop
  # do whatever you need with result
end
```

**Comment by opoudjis** [comment]
Moving to https://github.com/metanorma/metanorma-iso/issues/544 the issues with reference fetch parallelisation.

In this issue, I will do isodoc processing parallelisation.

**Comment by opoudjis** [comment]
The directories that isodoc writes to need to be unique for each extension; so alt_html and html under ISO need to write to distinct temp directories; and one thread cannot delete the temp directory another extension is using.

**Comment by opoudjis** [comment]
On new Mac, whole document now takes 14 min.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

As mentioned, could you please add an environment variable switch to turn parallelization off? 

This is due to packed-mn's usage of ruby-packer which will segfault at parallel file accesses.
