### ISSUE TITLE
Templates: harmonize and clean up

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#228]
1. Add `metanorma.yml` for all template repositories
2. Remove `:docfile: ...` from all files (this is a deprecated attribute now)
3. Add GHA workflows to run `metanorma site generate`.

**Comment by ronaldtse** [comment]
@manuel489 could you help with this? Thanks!

**Comment by ronaldtse** [comment]
As part of this task, we should add a metanorma.yml for them so that we can:

1. compile all templates as docs
2. provide rendered samples of the templates on GH pages

**Comment by manuel489** [comment]
> 1. Add metanorma.yml for all template repositories
> 2. Remove :docfile: ... from all files (this is a deprecated attribute now)

@ronaldtse, I have fulfilled these two tasks for the existent template repositories.

> 3. Add GHA workflows to run metanorma site generate.

This one remains.

**Comment by ronaldtse** [comment]
@manuel489 please help apply the same files from https://github.com/metanorma/mn-templates-ogc/pull/44 to all template repositories. Thanks!

**Comment by manuel489** [comment]
@ronaldtse, I've applied the changes in all templates. There are two flavors that fail on GHA: NIST and IETF.

In [NIST](https://github.com/metanorma/mn-templates-nist/pull/15), the error message is:
````
[metanorma] Error: loading gem `metanorma-nist` failed. Exiting.
````

While in [IETF](https://github.com/metanorma/mn-templates-ietf/pull/22):
````
[metanorma-ietf] Fatal: unable to generate txt, the command `xml2rfc` is not found in path.
[metanorma-ietf] Fatal: unable to generate html, the command `xml2rfc` is not found in path.
````

I'm able to locally compile documents without issue in both flavors though.

**Comment by ronaldtse** [comment]
@CAMOBAP can you help make these PRs work?

* [ ] https://github.com/metanorma/mn-templates-nist/pull/15
* [ ] https://github.com/metanorma/mn-templates-ietf/pull/22

**Comment by CAMOBAP** [comment]
Quick update:
1. https://github.com/metanorma/mn-templates-ogc/pull/46 - have a 'reference implementation'
1. I will propagate this approach to all template repos
1. Also this feature will be nice to implement https://github.com/metanorma/metanorma-cli/issues/268

**Comment by ronaldtse** [comment]
@CAMOBAP are the above items done? Thanks.

**Comment by CAMOBAP** [comment]
Almost I'm working to move matrix to external json for all mn-templates-*

**Comment by CAMOBAP** [comment]
Done, waiting for CI
 - https://github.com/metanorma/mn-templates-ogc/runs/4987802528
 - https://github.com/metanorma/mn-templates-cc/runs/4987787539

BTW CI matrix now very detailed so we will able to see from it exact document type in case of failure without need to doive into logs

**Comment by CAMOBAP** [comment]
small issue on windows fixed and CI passed
