### ISSUE TITLE
AsciiMath: Text below underbraces  (`ubrace`) get shifted

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma#235]
Text below underbraces gets shifted to right.

*Example:*
````
M = ubrace(((0.5, 0, 0.5),(0, 0.5, 0.5),(0, 0, 1)))_("Adjustment to texture space") cdot ubrace(((2f//w, 0, 0, 0),(0, 2f//h, 0, 0),(0, 0, 1, 0)))_("Perspective projection") cdot ubrace(((r_x, r_y, r_z,0),(u_x, u_y, u_z, 0),(d_x, d_y, d_z, 0),(0, 0, 0, 1)))_("Camera orientation") cdot ubrace(((1, 0, 0, -P_x),(0, 1, 0, -P_y),(0, 0, 1, -P_z),(0, 0, 0, 1)))_("Camera location")
````

*Generated with Metanorma:*
![issue2_generated](https://user-images.githubusercontent.com/33627611/149669493-8e1374c1-5420-4a0a-89b5-f1d9f8fd0d17.PNG)

*Original AsciiMath:*
![issue2_original](https://user-images.githubusercontent.com/33627611/149669503-67a62f70-4de6-4461-a97c-e1674aac7fa6.PNG)

**Comment by manuel489** [comment]
DOC output:
![issue2_generated_doc](https://user-images.githubusercontent.com/33627611/149669907-a0821999-a4cf-4cec-8e4d-a606b15bcd32.PNG)

**Comment by ronaldtse** [comment]
I can confirm that AsciiMath.JS has the same behavior. However I don't know if the `asciimath` gem does this or not.
<img width="868" alt="Screenshot 2022-01-17 at 1 12 19 AM" src="https://user-images.githubusercontent.com/11865/149670331-eb1ac211-4b45-4c03-a9fc-198f01e393e4.png">

**Comment by opoudjis** [comment]
`ubrace(X, Y)` is being rendered by the AsciiMath gem as `<msub>X Y</msub>`, instead of `<munder>X Y</munder>`.

That appears to be an oversight in AsciiMath gem: superscript and subscript with obrace and ubrace in AsciiMath are underscript nor subscript and overscript not subscript; just as with `lim_blah`.

**Comment by opoudjis** [comment]
Doing PR to asciimath gem

**Comment by opoudjis** [comment]
I have posted our kludge solution to riboseinc/asciimath, but hopefully the PR will be integrated into asciimath proper.

**Comment by opoudjis** [comment]
I will also implement the LaTeX version of this, Pepijn is too busy.

**Comment by opoudjis** [comment]
Implemented, waiting now on Pepijn.

**Comment by opoudjis** [comment]
Released
