### ISSUE TITLE
AsciiMath: Matrix not rendering inside fraction

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma#236]
*Markup:*
````
vec r = {((0,0,1))^T xx vec n}/{norm{((0,0,1))^T xx vec n}}
````

*Metanorma:*
![issue3_generated](https://user-images.githubusercontent.com/33627611/149670055-fec37e69-9882-4abe-a8a0-4fe2cb56391c.PNG)

*Original AsciiMath:*
![issue3_original](https://user-images.githubusercontent.com/33627611/149670060-d201ff26-684b-43ad-b2fd-975a1fab8910.PNG)

**Comment by manuel489** [comment]
DOC output:
![issue3_generated_doc](https://user-images.githubusercontent.com/33627611/149670124-e50f5217-706d-4a9c-82c6-7767dc8b9776.PNG)

In addition, vector arrows are shifted to the middle.

**Comment by opoudjis** [comment]
Matrixes don't render outside of fractions either: `((0,0,1))` renders with commas.

The asciimath gem expects to see `((0),(0),(1))` for matrices, and it also renders `((1,2,3),(4,5,6),(7,8,9))` correctly as a matrix. So `vec r = {((0),(0),(1))^T xx vec n}/{norm{((0),(0),(1))^T xx vec n}}` parses correctly.

That I believe is because of the gem requiring matrix expressions to end with parentheses, but requiring it too early. Raising ticket.

**Comment by opoudjis** [comment]
https://github.com/asciidoctor/asciimath/issues/71

**Comment by opoudjis** [comment]
In the case of Word...

... Ok, this is infuriating.

Our transformation of MathML to OOXML, using Microsoft's stylesheet, has `<m:chr m:val="&#x2192;">`, which uses the full-size right arrow: →

But what Word actually uses is `<m:chr m:val="⃗"/>`: they are using (unencoded) `&#x20D7`: a superscript arrow.

This issue also applies to Word renderings of hat x, ul x, tilde x.

I will address these by postprocessing in html2doc: I'm already having to do that for formatting with other OOXML there.

**Comment by ronaldtse** [comment]
> Our transformation of MathML to OOXML, using Microsoft's stylesheet, has `<m:chr m:val="&#x2192;">`, which uses the full-size right arrow: →
> 
> But what Word actually uses is `<m:chr m:val="⃗"/>`: they are using (unencoded) `&#x20D7`: a superscript arrow.
> 
> This issue also applies to Word renderings of hat x, ul x, tilde x. I need to use superscript versions of the characters for each of those in OOXML.

@opoudjis are you sure this should go into html2doc rather than our OMML gem?

**Comment by opoudjis** [comment]
Asciimath fixed to address issue.

@ronaldtse: our OMML gem transforms OOXML to MathML. This conversion is the opposite direction; we don't have a MathML to OOXML gem, that mapping is currently only contained in the html2doc gem. I don't see a pressing need to factor it out, but if you do, please delegate the task :)
