### ISSUE TITLE
AsciiMath: `frac{}{}` macro not rendering

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma#237]
````
[stem%unnumbered]
++++
I = frac{bh^{3}}{12}
++++
````

Generated:

![eq_generated](https://user-images.githubusercontent.com/33627611/151214994-db66f7b1-58f9-4969-839c-702583dba45d.PNG)

Original:
![eq_original](https://user-images.githubusercontent.com/33627611/151215003-3c04fcd4-ee4f-4690-a78e-2cd0a8227d9c.PNG)

**Comment by ronaldtse** [comment]
I confirm that this works with asciimath.org but not sure about the asciimath gem.

**Comment by opoudjis** [comment]
Raised https://github.com/asciidoctor/asciimath/issues/70

**Comment by opoudjis** [comment]
Addressed in asciimath.
