### ISSUE TITLE
Unable to install metanorma via brew

### ISSUE THREAD

**Issue by caitlinadams** [metanorma/metanorma#244]
I attempted to install metanorma on MacOS using the simple instruction here: https://www.metanorma.org/install/macos/

namely `brew install metanorma/metanorma/metanorma`

I received the following warning, and metanorma was not installed.
```
Warning: No available formula with the name "git" (dependency of metanorma/metanorma/metanorma).
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I'm not sure why this is occurring and don't have enough knowledge of brew to chase down what might be going wrong. 

I am using a MacBook with an Apple M1 Chip. If I need to use a different method to install metanorma, please let me know.

**Comment by ronaldtse** [comment]
@caitlinadams sorry for the delay in replying! It might be that our Homebrew formula is outdated. @CAMOBAP can you help here? Thanks!

**Comment by ronaldtse** [comment]
This is actually very strange because it seems that even our builds these few days have had trouble with the Homebrew "git" formula? e.g. https://github.com/metanorma/homebrew-metanorma/runs/6768026198?check_suite_focus=true

**Comment by CAMOBAP** [comment]
It looks like something is broken in the brew installation because git formula definitely exists https://formulae.brew.sh/formula/git

@caitlinadams could you please run:
 - `brew update`
 - `brew doctor`
 - `brew config`

And attach files with output here?

**Comment by caitlinadams** [comment]
Thanks for getting back to me, I have attached here. I think you're right that the brew install might be broken. The doctor output contains:
```
Warning: Homebrew/homebrew-core was not tapped properly! Run:
  rm -rf "/opt/homebrew/Library/Taps/homebrew/homebrew-core"
  brew tap homebrew/core
```

Shall I try running this and then re-installing metanorma? 

[brew_config.txt](https://github.com/metanorma/metanorma/files/8876185/brew_config.txt)
[brew_doctor.txt](https://github.com/metanorma/metanorma/files/8876186/brew_doctor.txt)
[brew_update.txt](https://github.com/metanorma/metanorma/files/8876187/brew_update.txt)

**Comment by CAMOBAP** [comment]
@caitlinadams yes, I think so, and run doctor and update after it so full script should be like:

```
rm -rf "/opt/homebrew/Library/Taps/homebrew/homebrew-core"
brew tap homebrew/core
brew doctor
brew update
brew install metanorma/metanorma/metanorma
```

**Comment by ronaldtse** [comment]
@caitlinadams could you first try those commands? Seems that the failure was due to the Homebrew install not having fully cloned the core formulas.

**Comment by CAMOBAP** [comment]
@caitlinadams feel free to reopen if you still have issues with installation, thanks
