### ISSUE TITLE
Raise minimum Ruby version to 2.7 due to EOL

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#264]
As per: https://github.com/metanorma/ci/blob/main/.github/workflows/generic-rake.yml

We are no longer testing Metanorma on Ruby 2.6. However, the gemspec files still state a minimum Ruby version on 2.5.

This task is to update all the gemspec files to state a min requirement of Ruby 2.7.

Ruby 2.6 has been EOLed:
https://www.ruby-lang.org/en/downloads/branches/
<img width="282" alt="Screen Shot 2022-10-26 at 7 04 15 PM" src="https://user-images.githubusercontent.com/11865/198010348-ca5dad92-4804-4dda-adeb-c2bd0c4d5fa6.png">

**Comment by opoudjis** [comment]
Updated all the gems I'm involved with.

**Comment by ronaldtse** [comment]
@opoudjis we're still missing the `metanorma-*` gems though.

**Comment by maxirmx** [comment]
[pngcheck](https://github.com/metanorma/pngcheck-ruby)  was 2.7 already
[ffi-libarchive-binary](https://github.com/fontist/ffi-libarchive-binary) was 2.7 already
[excavate](https://github.com/fontist/excavate) was 2.7 already 
[expressir](https://github.com/lutaml/expressir) -- upgraded
[extract_ttc](https://github.com/fontist/extract_ttc) -- upgraded
[emf2svg](https://github.com/metanorma/emf2svg-ruby) -- TODO buiild is broken, not related to Ruby version, something wrong with vcpkg on alpine
[fontist](https://github.com/fontist/fontist) -- TODO something is broken

**Comment by opoudjis** [comment]
> @opoudjis we're still missing the `metanorma-*` gems though.

They're done locally, you'll get them next release.
