### ISSUE TITLE
Metanorma needs not to recover from errors in Presentation XML

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#270]
We currently have this code triggered by crashes in isodoc:

````
    def process_output_threaded(ext, fnames1, options1, isodoc_options1)
      @processor.output(nil, fnames1[:presentationxml], fnames1[:out], ext,
                        isodoc_options1)
      wrap_html(options1, fnames1[:ext], fnames1[:out])
    rescue StandardError => e
      isodoc_error_process(e)
    end

    def isodoc_error_process(err)
      if err.message.include? "Fatal:"
        @errors << err.message
      else
        puts err.message
        puts err.backtrace.join("\n")
      end
    end
````

I'm not generating errors with "Fatal:" in them, and any errors that have surfaced here from isodoc are going to be catastrophic; for example, they are errors that are resulting in Presentation XML not being generated at all.

I'm going to make all errors triggered by Presentation XML fatal, since they compromise downstream generation. We should have a strict abort mode on metanorma, that makes all errors fatal when we are running docker testing.

**Comment by opoudjis** [comment]
Not releasing just yet, need to create strict mode.

Also not releasing because this is going to end up causing lots of crashes on docker test run, which I'll deal with when people are more available.

**Comment by opoudjis** [comment]
Need to implement `metanorma site generate --strict`, and have it propagate `strict` down to individual compilations.

**Comment by CAMOBAP** [comment]
> Need to implement `metanorma site generate --strict`, and have it propagate `strict` down to individual compilations.

Already done
