### ISSUE TITLE
(URGENT) Template repository CI runs failing on setup-ruby

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#275]
All the template repositories need to have their CI scripts updated, e.g.:
* https://github.com/metanorma/mn-templates-ogc/actions/runs/4079122511
* https://github.com/metanorma/mn-templates-itu/actions/runs/4079122612
* https://github.com/metanorma/mn-templates-iso/actions/runs/4079122573
* https://github.com/metanorma/mn-templates-iec/actions/runs/4079122692
* https://github.com/metanorma/mn-templates-nist/actions/runs/4079122459
* etc.

**Comment by CAMOBAP** [comment]
Not relevant anymore because another approach is implemented https://github.com/metanorma/metanorma-cli/issues/273
