### ISSUE TITLE
input stopped working

### ISSUE THREAD

**Issue by jonsneyers** [metanorma/metanorma#290]
Hi, I am getting an error for something that used to work before:

```
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/plurimath-0.3.0/lib/plurimath/math.rb:51:in `rescue in parse': An error occurred while processing the input. Please check your input to ensure it is valid or open an issue on Github If you believe the input is correct. (Plurimath::Math::Error)
---- INPUT START ----
  \\[out_k = \\frac{1}{s}\\left(k == 0 ? 1 : \\sqrt{2}\\right)\\sum_{n = 0}^{s - 1}{in_{n} \\cdot \\cos\\left( \\frac{\\pi k}{s}\\left( n + \\frac{1}{2} \\right) \\right)}\\]
---- INPUT END ----
```

**Comment by jonsneyers** [comment]
Is there a workaround for this?

Or alternatively, is there some way to downgrade my metanorma version so I can get my spec compiled again? I'm using snap and it's nice that things get auto-updated but in this case I would prefer to go back to last week's version because then this still worked :)

**Comment by ronaldtse** [comment]
Sorry @jonsneyers for this issue…

@CAMOBAP do you have any advice for snap downgrades?

This issue looks like a Plurimath problem — we recently changed the math processing engine which we thought was reasonably mature, but it’s still running into issues. 

We’ll try to release a new version as soon as we can.

**Comment by jonsneyers** [comment]
Thanks for the quick response. The 99th JPEG meeting is taking place and we're trying to produce the DIS for the 2nd edition of 18181-1 and I just ran into this problem, so you can imagine the timing is not so great for me. But the final plenary of the meeting is still two days from now so that's about the time window we have available to get this sorted out (unless we request an editing period, then we have up to two more weeks, but we weren't planning to do that).

**Comment by CAMOBAP** [comment]
> do you have any advice for snap downgrades?

Unfortunatelly snapcraft doesn't allow downgrade snaps(

Probably a single option here is to proceed with the previous docker image https://hub.docker.com/layers/metanorma/metanorma/1.7.0/images/sha256-15512057cbdec0f9a7a0500edb390fa3ade9625c72bf87ab4e12030a82cb07cb?context=explore

**Comment by ronaldtse** [comment]
If the snap package of the previous version is already installed, would this work?

https://askubuntu.com/questions/1198022/how-to-run-a-previous-version-of-a-snap-package

**Comment by CAMOBAP** [comment]
@ronaldtse good point, it might work, worth a try

**Comment by ronaldtse** [comment]
@CAMOBAP can you help update or provide documentation on how to downgrade a snap package? Thanks.

**Comment by opoudjis** [comment]
@ronaldtse You need to answer this question

**Comment by ronaldtse** [comment]
@CAMOBAP can you make it a new blog post on the snap package:
- how to install using snap
- how to upgrade using snap
- how to downgrade using snap

? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse ready for review https://github.com/metanorma/metanorma.org/pull/726
