### ISSUE TITLE
Document default crossref style doesn't work

### ISSUE THREAD

**Issue by jonsneyers** [metanorma/metanorma#292]
`:xrefstyle: basic`

does not seem to do anything. Styling individual references works, but setting a default for the whole document doesn't seem to work.

**Comment by ronaldtse** [comment]
@jonsneyers In ISO, the document’s xref style is fixed according to ISO DIR 2.

**Comment by jonsneyers** [comment]
Yes, but this also happens when using `:mn-document-class: generic`.

I'm considering to also use metanorma for something that is not a spec but a more informal type of documentation, but I'd prefer to not have cross-references that are automatically styled as "Clause 6.2" etc instead of just a clickable link with the name of the section.

**Comment by ronaldtse** [comment]
Thank you for the additional context. Currently `generic` actually uses ISO DIR 2 defaults.

We are actually seeing increasing adoption of `generic` as a customizable flavor / simple usage of Metanorma, so please let us discuss internally and revert here. Thanks!

**Comment by opoudjis** [comment]
Oversight on my part. This is implemented fine, if you generate the document via asciidoctor; but if you run it as we recommend, using the metanorma command line, the `:xrefstyle:` document attribute is not detected. Fixing.
