### ISSUE TITLE
How to prevent replacement for `--`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#297]
Source issue: https://github.com/metanorma/stepmod2mn/issues/36#issuecomment-1568230695

Source adoc:
```
--:: the text following is a comment or introduces a clause reference;
```

Expected result:
![image](https://github.com/metanorma/metanorma/assets/5559926/b3871202-5f9d-4b1d-953e-100468f22b13)

I've tried to escape `--` by:
```
\--:: the text following is a comment or introduces a clause reference;

+++--+++:: the text following is a comment or introduces a clause reference;

pass:[--]:: the text following is a comment or introduces a clause reference;
```

but in all case the Presentation XML contains em dash (U+2014):
`<dt>—</dt>`

**Comment by ronaldtse** [comment]
It seems that there is some encoding issue here, why would anyone want a `--` in a definition term?

**Comment by Intelligent2013** [comment]
> It seems that there is some encoding issue here, why would anyone want a `--` in a definition term?

From the source HTML, the section 5.1 `5.1 Mapping specification`:
![image](https://github.com/metanorma/metanorma/assets/5559926/76ec7a7c-cdb4-48e4-9107-c8f990f6794c)

The solution:
```
pass-format:all[--]:: the text following is a comment or introduces a clause reference;
```
