### ISSUE TITLE
Table formatting issues/questions

### ISSUE THREAD

**Issue by ccrook** [metanorma/metanorma#308]
Possibly two issues.   I am trying to create a table with two rows of header, and footnotes.

At the moment I have the following code:

```
[[table-time-function-attributes]]
.Time function mandatory (M) and optional (O) attributes
[options="header"]
[valign="top"]
[cols="<,7^]
|=== 
| Function type  7+^h| Attribute

// Second heading line.
| 
^| Reference epoch footnote:tfepoch[Epochs may be specified as a date/time or epoch in decimal years] 
^| Start epoch footnote:tfepoch[] 
^| End epoch footnote:tfepoch[] 
^| Event epoch footnote:tfepoch[] 
^| Time constant footnote:[A time constant is in  years] 
^| Frequency footnote:[A frequency is specified in cycles per year] 
^| Scale factor

// Type             ^| Ref ^| Sta ^| End ^| Evt ^| TmC ^| Frq ^| Scl 
| velocity          ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| acceleration      ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| step              ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| ramp              ^|  -  ^|  M  ^| M   ^|  -  ^|  -  ^|  -  ^|  O
| exponential       ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| logBaseE          ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| logBase10         ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| hyperbolicTangent ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| cyclic            ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  M  ^|  O

|
```

Issue 1:

I haven't figured out a way of making the second heading line part of the heading.   I can change the cell type to <th> in HTML using h| instead of h in the markdown, but this doesn't get reflected in the styling other than that the text is converted to upper case and bold.  The background is not changed, and the second line does not appear in headings on subsequent pages if the table spans a page boundary. 

This may not be addressable in metanorma as it appears to be an asciidoc issue https://github.com/asciidoctor/asciidoctor/issues/1687.

Issue 2:
Related to issue 1, I tried to merge the first two columns of the first row but haven't been able to find a syntax for this.  Everything I have tried creates more or less significant table layout changes.  

Issue 3:
A footnote to a table header is rendered in upper case.  This is very undesirable!  Occurs if second row cells are introduced with h| instead of just | above (or if footnotes added to item in the first (header) row of the table

Issue 4:
_Not really an issue but just raising in case someone can offer a better suggestion._  I tried using the cols= attribute to set the [cols="<,7^] attribute to set the column alignment to centred but it didn't seem to work, possibly a syntax error?

Issue 5:
_Not really an issue._  This would possibly be better posted to a mailing list or other user forum, but I couldn't find a reference to one on the [metanorma.org](https://metanorma.org) or index page of this repository :-(

**Comment by opoudjis** [comment]
Issue 1:

Asciidoctor does not allow two header rows, but we allow them in Metanorma: add the Metanorma-specific option `headerrows=2`

https://www.metanorma.org/author/topics/document-format/text/#tables

````
[[table-time-function-attributes]]
.Time function mandatory (M) and optional (O) attributes
[options="header"]
[valign="top"]
[cols="<,7^]
[headerrows=2]
|=== 
| Function type  7+^h| Attribute

// Second heading line.
| 
^| Reference epoch footnote:tfepoch[Epochs may be specified as a date/time or epoch in decimal years] 
^| Start epoch footnote:tfepoch[] 
^| End epoch footnote:tfepoch[] 
^| Event epoch footnote:tfepoch[] 
^| Time constant footnote:[A time constant is in  years] 
^| Frequency footnote:[A frequency is specified in cycles per year] 
^| Scale factor

// Type             ^| Ref ^| Sta ^| End ^| Evt ^| TmC ^| Frq ^| Scl 
| velocity          ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| acceleration      ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| step              ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  -  ^|  O
| ramp              ^|  -  ^|  M  ^| M   ^|  -  ^|  -  ^|  -  ^|  O
| exponential       ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| logBaseE          ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| logBase10         ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| hyperbolicTangent ^|  -  ^|  O  ^| O   ^|  M  ^|  M  ^|  -  ^|  O
| cyclic            ^|  M  ^|  O  ^| O   ^|  -  ^|  -  ^|  M  ^|  O

````

**Comment by opoudjis** [comment]
Issue 2:

> Related to issue 1, I tried to merge the first two columns of the first row but haven't been able to find a syntax for this. Everything I have tried creates more or less significant table layout changes.

... I don't see why. This is what I get for:

````
|===
+^| Function type  7+^h| Attribute
2+^| Reference epoch footnote:tfepoch[Epochs may be specified as a date/time or epoch in decimal years] 
^| Start epoch footnote:tfepoch[]
^| End epoch footnote:tfepoch[] 
^| Event epoch footnote:tfepoch[]
^| Time constant footnote:[A time constant is in  years] 
^| Frequency footnote:[A frequency is specified in cycles per year]
^| Scale factor
````

HTML:
<img width="1016" alt="Screenshot 2023-08-02 at 20 27 59" src="https://github.com/metanorma/metanorma/assets/1911039/06040516-f65a-448b-bbd9-4de5b99d47da">

DOC:
<img width="805" alt="Screenshot 2023-08-02 at 20 32 13" src="https://github.com/metanorma/metanorma/assets/1911039/263cbe44-b94d-4594-9333-b23c02b719bc">


PDF:
<img width="482" alt="Screenshot 2023-08-02 at 20 33 04" src="https://github.com/metanorma/metanorma/assets/1911039/4437e6fc-d4ba-4d94-b055-5d8b94a5bbca">


If you're trying to do something else, please let me know, but if you've got that amount of text to fit into a table, and you're going to change the alignment of multi-column cells in two distinct header rows, the result will look odd. If anything, I'm pleasantly surprised how these have turned out...

**Comment by opoudjis** [comment]
Issue 4:

> Not really an issue but just raising in case someone can offer a better suggestion. I tried using the cols= attribute to set the [cols="<,7^] attribute to set the column alignment to centred but it didn't seem to work, possibly a syntax error?

https://docs.asciidoctor.org/asciidoc/latest/tables/align-by-column/#horizontal-operators

Indeed it is. The correct syntax is `[cols="<,7*^]`, and I've just confirmed that it works.

**Comment by opoudjis** [comment]
Issue 5:

We don't have an active user forum *yet*, although we know that uptake from OGC is such that we're about to need one. Unfortunately it is not unusual for me to take weeks to get to issues, which makes the need for an active user forum all the more pressing. I'll look into getting one up.

**Comment by ccrook** [comment]
@opoudjis Thankyou for all this feedback, and apologies for multiple issues in one item.   I wasn't aware of metanorma-ogc, so thanks for the pointer.

On the table formatting,  Thanks so much.  I'd hadn't spotted the metanorma specific headerrows option.  That is exactly what I need.
