### ISSUE TITLE
Code blocks inside requirement parts?

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma#312]
What is the proper way to include code blocks inside a requirement part?

In https://raw.githubusercontent.com/opengeospatial/ogcapi-tiles/master/core/standard/requirements/core/REQ_tc-tilematrix-definition.adoc I see that a completely different, very cumbersome syntax is used with `[requirement, ...]` and `[.component,class=part...]` within which a `[source,YAML]` is found.

Is there another way sticking to the usual `::part`, at least for the other requirement parts that do not need a code block inside, and using  `label::`?

This is an issue we are struggling with in https://github.com/jerstlouis/ogcapi-discrete-global-grid-systems/blob/master/core/requirements/requirements_class_zone-query.adoc .

Thanks!

cc @ronaldtse @ghobona @rggibb @geofizzydrink

**Comment by opoudjis** [comment]
The metadata about requirements is an Asciidoctor definition list. Therefore, if you want to include multiple blocks of content in a definition list, you use list continuation and an open block, to group that content together as a single block:

https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/#list-continuation

````
[requirement]
====
[%metadata]
label:: /req/zone-query/bbox
description:: For specifying a spatial bounding box for which to return a list of DGGS zones:
part::
+
--
The Implementation SHALL support a `bbox` query parameter for the zone query
operation (resource path ending with `.../dggs/{dggsId}/zones`) with the characteristics defined in the OpenAPI Specification 3.0 fragment

[source,YAML]
----
  bbox:
    name: bbox
    in: query
    description:
      Bounding box of the rendered map. The bounding box is provided as four or six coordinates

      * Lower left corner, coordinate axis 1
      * Lower left corner, coordinate axis 2
      * Minimum value, coordinate axis 3 (optional)
      * Upper right corner, coordinate axis 1
      * Upper right corner, coordinate axis 2
      * Maximum value, coordinate axis 3 (optional)

      The coordinate reference system and axis order of the values are indicated in the `bbox-crs` parameter or if the parameter is missing in http://www.opengis.net/def/crs/OGC/1.3/CRS84
    required: false
    schema:
      type: array
      oneOf:
      - minItems: 4
        maxItems: 4
      - minItems: 6
        maxItems: 6
      items:
        type: number
        format: double
    style: form
    explode: false
----
--
````

<img width="1575" alt="Screenshot 2023-09-07 at 21 11 50" src="https://github.com/metanorma/metanorma/assets/1911039/ca7ebe33-0582-4cb3-91cc-0fd05f4cd3be">

**Comment by jerstlouis** [comment]
@opoudjis Thank you very much!
