### ISSUE TITLE
bibliographic entry using DOI in asciidoc not rendering as expected (IEEE SA flavor)

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma#328]
looking to use the DOI fetch for preparing bibliographic entries, i am noticing that the render is not following the IEEE SA Style guide.

this is the current code: (based on https://github.com/metanorma/metanorma.org/pull/694/files)

`* [[[ref_pddl,doi:10.1007/978-3-031-01584-7]]]`

the rendered output:

![Spatial_Web_Protocol_Architecture_and_Governance_-_2023-09-25_23_20_26](https://github.com/metanorma/metanorma/assets/35089343/fab1ca20-32eb-4d83-b0d5-037d0bba57aa)

the main issue is the DOI reference at the start of the entry. the rest of the entry, in my understanding, renders correctly, however there could be a minor issue with the identifier for the DOI reference at the end. 

the only DOI reference in the IEEE SA Style guide is this:

![image](https://github.com/metanorma/metanorma/assets/35089343/98211dc9-4cde-4cc3-92de-a49f356a584e)

it is specific to an "open source" type of citation, i would expect it to be the same for a book/article.

the DOI fetch option is very useful and will save a lot of time and also clean up a bibliography.

i wanted to include the metanorma version i am using but i dont know where to find that info.  i use metanorma through a github toolchain. it works very well.  tell me where i can find the metanorma version so i can provide you with more information.

thank you.

**Comment by opoudjis** [comment]
DOI is being treated erroneously as an SDO (standards organisation) identifier, which is being added before citations.

DOI needs to allowed in IEEE citations as an alternative to URI.

**Comment by ReesePlews** [comment]
thank you for investigating and taking care of this @opoudjis !
