### ISSUE TITLE
Font specification of inline/block text (not `css font-family`)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#339]
From https://github.com/metanorma/pdfa-iso-32000-2/issues/11 , a feature was implemented to allow specifying ad-hoc CSS to Metanorma input.

```
[css font-family:"Zapf Dingbats"]#&#xF025;#
[css font-family:"Zapf Dingbats"]#&#xF045;#
```

However, as we well know, only HTML supports CSS. PDF, Word do not support CSS.

Hence there is a need to generalize font specification into this:
```
[font:"Zapf Dingbats"]#&#xF025;#
[font:"Zapf Dingbats"]#&#xF045;#
```

**Comment by opoudjis** [comment]
I have repeatedly told you why I refuse to implement a new formatting language from scratch (which "font:" is the first unwelcome harbinger of), and using CSS as a formatting language does not necessitate implementing it as CSS at all.

You are not acknowledging my reasoning, you are just ignoring it,  and every couple of months telling me to do an ad hoc change, and I am not doing ad hoc changes to Metanorma any more.

Until we discuss this, I am refusing to action this.

**Comment by ronaldtse** [comment]
“font” is clearly not anything connected with a formatting language. It is just an extension of bold and strikethrough. Let’s not blow it out of proportion. 

In any world in can conceive of “parsing CSS” would be a nightmare for any format.

**Comment by opoudjis** [comment]
Because you are going to come to me next months and ask for colour or background colour or god knows what else, I am going to implement a reasonable subset of the inline formatting commands of CSS. YOU WILL NOT GET `font:[]` from me.

**Comment by ronaldtse** [comment]
@opoudjis a `[font: ... color: ... underline:...]#...#` type of macro could work like `[underline]#...#`.

**Comment by opoudjis** [comment]
We have agreed that the semantic XML shall express, not a font, but the agreed custom character set of the Private Unicode codepoint, which is what the actual agreed semantics of the private codepoint is dictated by; the font realises that agreement, but is not the actual semantics of the agreement. We will add the font that the custom character set shall be rendered in as a processing hint.

We need inline formatting in Presentation XML still, including for this. For now, we will keep the Presentation XML font in CSS; ultimately we will move to something... more broken down, capturing a wider range of inline rendering. But not yet.

So:

````
:character-convention-font: weather:"OGC Weather Symbols"

[char-convention: weather]#xyz#
````

Where `[char-convention: weather]#xyz#` is going to be part of a more general pattern of inline formatting, like `[font: ... color: ... underline:...]#...#`

This will be rendered in Presentation XML still as `<span style="...."/>`, so downstream processors of Presentation XML do not (yet) need to change.

**Comment by opoudjis** [comment]
The attached correctly displays the Klingon letter for A, marked up as:

````
= A
:docsubtype: vocabulary
:subdoctype: vocabulary
:presentation-metadata-custom-charset-font: weather:"Code2000"
:fonts: "Code2000"

== Clause

[custom-charset: weather]#&#xf8d0;#
````

Because fontist does not know Code2000, it isn't rendering in PDF, but the solution builds on the existing implementation in PDF of fonts, so this been successfully implemented.

**Comment by opoudjis** [comment]
:presentation-metadata-custom-charset-font: is a comma-delimited list of charset/font pairs.
