### ISSUE TITLE
Image sizing in Metanorma not consistent with core AsciiDoc

### ISSUE THREAD

**Issue by lrosenthol** [metanorma/metanorma#354]
To give an image an explicit width/height in Metanorma, you need to put the values on a separate line from the `image:` element, as described [here](https://www.metanorma.org/author/topics/document-format/text/#image-size).

```
[width=284,height=424]
image::Photo_Manifest.{image-ext}[Example C2PA Manifest of a Photograph,align="center"]
```

Whereas in AsciiDoc, it should be inline in the attributes of the image, as described [here](https://docs.asciidoctor.org/asciidoc/latest/macros/image-size/).

```
image::Photo_Manifest.{image-ext}[Example C2PA Manifest of a Photograph,width=284,height=424,align="center"]
```

**Comment by opoudjis** [comment]
Both 

````
image::images/figure-path.png[Example C2PA Manifest of a Photograph,align="center",width=142,height=212]
````

and 

````
[align="center",width=142,height=212]
image::images/figure-path.png[Example C2PA Manifest of a Photograph]
````

generate identical output in both Metanorma:

````
<figure id="_44f6cb0e-86b0-ef0a-a925-cd353e5426f7"><image src="images/figure-path.png" mimetype="image/png" id="_8f8d25cd-1ad9-0fdc-cc99-accf53e0f445" height="212" width="142" alt="Example C2PA Manifest of a Photograph"/></figure>

<figure id="_1f271083-5e93-a930-aa89-341674d3ac2a"><image src="images/figure-path.png" mimetype="image/png" id="_570dfc3b-e4f2-3e33-be77-a7d390051b76" height="212" width="142" alt="Example C2PA Manifest of a Photograph"/></figure>
````

and native Asciidoctor:

````
div class="imageblock text-center">
<div class="content">
<img src="images/figure-path.png" alt="Example C2PA Manifest of a Photograph" width="142" height="212">
</div>
</div>
<div class="imageblock text-center">
<div class="content">
<img src="images/figure-path.png" alt="Example C2PA Manifest of a Photograph" width="142" height="212">
</div>
</div>
````

So your statement is incorrect. There is no requirement on operating code that the attributes be inline as opposed to on block level, that comes from Asciidoctor code. The only issue here is that the Asciidoctor documentation currently doesn't mention the latter option in https://docs.asciidoctor.org/asciidoc/latest/macros/image-size/

I am going to action this to future-proof our documentation, but we are not resourced to do this level of intervention on documentation. (We do not have a documentation manager.) So requests to fix documentation that is not actually broken are not normally going to be prioritised...
