### ISSUE TITLE
Image resizing of SVG image does not work

### ISSUE THREAD

**Issue by lrosenthol** [metanorma/metanorma#355]
Given a large SVG image, such as the attached one, and a statement to resize it - nothing happens.  The image is still full page width in the output PDF.

```
[width=142,height=212]
image::Photo_Manifest.svg[Example C2PA Manifest of a Photograph,align="center"]
```

I believe this may be related to https://github.com/metanorma/ht[ml2doc/issues/44

![Photo_Manifest](https://github.com/metanorma/metanorma/assets/5074741/118bebd2-d8b9-4469-979b-3c2258f851ea)

Version info
```
lrosenth@Leonards-MBPro-2021 specs-core-iso % metanorma --version
Metanorma 1.7.0
Metanorma::Cli 1.9.0
Metanorma::Standoc 2.8.0/IsoDoc 2.8.0
Metanorma::ISO 2.7.0
Metanorma::Iec 2.4.0
Metanorma::IEEE 1.2.0
Metanorma::Ietf 3.3.0
Metanorma::Generic 2.6.0
Metanorma::BIPM 2.4.0
Metanorma::CC 2.4.0
Metanorma::Csa 2.4.0
Metanorma::IHO 0.9.0
Metanorma::JIS 0.2.0
Metanorma::UN 0.12.0
Metanorma::Ogc 2.5.0
Metanorma::ITU 2.4.0
```

**Comment by lrosenthol** [comment]
FWIW processing the same file directly through AsciiDoctor produces the correct results.

**Comment by ronaldtse** [comment]
Thanks @lrosenthol  for the report. 

@Intelligent2013 any thoughts here?

**Comment by Intelligent2013** [comment]
XSLT updated:
![image](https://github.com/metanorma/metanorma/assets/5559926/2a58ff49-5a50-41f0-bef2-80964303e1ba)

So the remaining task is fixing `height="auto" width="auto"`.

**Comment by lrosenthol** [comment]
@Intelligent2013 Thanks!   

FYI, using standard AsciiDoc image sizing (aka inline the attributes section) doesn't work either, which is one of the reasons I also filed #354

**Comment by opoudjis** [comment]
> So the remaining task is fixing `height="auto" width="auto"`.

So I understand: the request is to ensure that the specified height and width parameters are not ignored, right? Because if they are not specified at all, the use of "auto" is legitimate.

**Comment by Intelligent2013** [comment]
> > So the remaining task is fixing `height="auto" width="auto"`.
> 
> So I understand: the request is to ensure that the specified height and width parameters in Asciidoc are not ignored, right? Because if they are not specified at all, the use of "auto" is legitimate.
> 
> I strongly suspect this is a bug specific to SVGs, which are handled separately from other images.

For adoc:
```adoc
[width=142,height=212]
image::images/Photo_Manifest.svg[Example C2PA Manifest of a Photograph,align="center"]
```
The presentation XML contains `height="auto" width="auto"`:
```xml
<figure id="_e45bcffb-ecfe-ce87-cd9c-45c10b0feb45">
	<name>Figure A.3</name>
	<image src="" mimetype="image/svg+xml" height="auto" width="auto">
		<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
```
but expected `<image src="" mimetype="image/svg+xml" height="212" width="142">`

**Comment by opoudjis** [comment]
I have been replacing the image node with the svg node in Semantic XML:

Before:

````
<figure id="_6d481e45-aa84-4fcb-5259-9c12a48d368d">
<image src=\"images/fig-1.svg\" mimetype=\"image/svg+xml\" id=\"_46c2554a-0fc5-40ff-b88b-e79646065fd5\" height=\"212\" width=\"142\" alt=\"Example C2PA Manifest of a Photograph\"/>
....
````

After:

````
<figure id="_6d481e45-aa84-4fcb-5259-9c12a48d368d">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="uuid-70e44de8-1e8b-4065-9088-d0e974ab62b5" viewBox="0 0 248.89 236.8">
....
````

And in Presentation XML, I end up putting a new `<image>` wrapper back in.

But in the process, all the original `image` attributes have been lost. Now, I am translating those height and width attributes into the SVG viewbox. But I'm going to keep the image wrapper, and confirm that it works.

**Comment by opoudjis** [comment]
@Intelligent2013 can you confirm that this output is as you expect?

[Archive 5.zip](https://github.com/metanorma/metanorma/files/14512200/Archive.5.zip)

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can you confirm that this output is as you expect?
> 
> [Archive 5.zip](https://github.com/metanorma/metanorma/files/14512200/Archive.5.zip)

@opoudjis confirmed. Thank you!
