### ISSUE TITLE
Metanorma install (via Mac homebrew) has VERY OLD PlantUML

### ISSUE THREAD

**Issue by lrosenthol** [metanorma/metanorma#356]
November 30, 2020: [Easily display your JSON data (V1.2020.21).](https://plantuml.com/json)

This feature is not supported in the version of PlantUML used by Metanorma when installed via homebrew on MacOS - I verified that both my Metanorma and my PlantUML were up to date.

This can easily be verified by adding this to an AsciiDoc file and running through Metanorma

```
[plantuml,target=Entities,format=svg,width=612,align="center"]
....
@startuml
allowmixing

json Template {
	"action": "com.joesphoto.filter",
	"description": "Magic Filter",
	"digitalSourceType": "http://cv.iptc.org/newscodes/digitalsourcetype/compositeSynthetic",
	"softwareAgent" : [{
		"name": "Joe's Photo Editor",
		"version": "2.0",
		"schema.org.SoftwareApplication.operatingSystem": "Windows 10"
	}]
}
@enduml
....
```

**Comment by ronaldtse** [comment]
@lrosenthol thank you for the report. I assume that you've been using Metanorma installed via Homebrew?

If so, the formula is [here](https://github.com/metanorma/homebrew-metanorma/). 

The particular dependency of `plantuml` is located in the Formula:
* https://github.com/metanorma/homebrew-metanorma/blob/b5a390a75e0f28babe74316ed86397f83bb1ffb5/Formula/metanorma.rb#L23

The challenge here is to find out why an older PlantUML is being used.

Pinging @opoudjis @CAMOBAP for help.

**Comment by CAMOBAP** [comment]
@ronaldtse @lrosenthol `metanorma` don't restrict `plantuml` version and it can be updated independently by `brew upgrade plantuml`

**Comment by opoudjis** [comment]
Outside my bailiwick. It is indeed the case that nothing in metanorma-standoc says anything about plantuml versioning, it is presupposed as an external installation. I run brew upgrade periodically, and my plantuml is "PlantUML version 1.2023.13 (Tue Dec 12 05:20:57 AEDT 2023)" Not something I can shed light on.

**Comment by lrosenthol** [comment]
My PlantUML is also 
```
PlantUML version 1.2024.3 (Thu Feb 15 14:40:05 EST 2024)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US
 
PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 9.0.0 (20230911.1827)
Installation seems OK. File generation OK
```
but when I process the fragment above, I get an error on line 4 - where the `json` statement is.  The same fragment works fine natively in PlantUML and also from AsciiDoctor Diagram...

**Comment by CAMOBAP** [comment]
@lrosenthol thanks for details, let me doublecheck

**Comment by lrosenthol** [comment]
To add some additional info here - it's NOT just the Mac install.

Using the Metanorma 1.9.0 Docker container (`metanorma/metanorma:1.9.0`), I end up with the same results trying to process the same fragment.

**Comment by lrosenthol** [comment]
Also current version of Metanorma docker container also reports the same errors.

>Error line 4 in file: /tmp/plantuml20240310-1-12wcyd.pml
>Some diagram description contains errors

**Comment by ronaldtse** [comment]
@CAMOBAP any updates here?

**Comment by CAMOBAP** [comment]
Sorry for the late update:

1. `brew` has `plantuml` without any version restrictions
2. `metanorma` binary which is installed with `brew` don't embed `plantuml` in it (checked `packed-mn` with `--tebako-extract`)
3. to lookup `plantuml` binary `metanorma` check both `PATHEXT` and `PATH` environment variables

### Next step to troubleshooting

1. Try this command on macOS `locate plantuml | grep /plantuml$`
2. And double-check versions of found `plantuml` instances
3. Depends environment settings there still some old `plantuml` may be pick up first

**Comment by lrosenthol** [comment]
@CAMOBAP That makes sense for my local install - will do that, thanks!

Any idea why the same problem happens with the official Metanorma Docker container?

**Comment by lrosenthol** [comment]
@CAMOBAP Then why would using that fragment in an AsciiDoc file run via the Docker container throw an error - and then not produce any image :(.   I can put together a small sample/test for you if you need.

**Comment by CAMOBAP** [comment]
@lrosenthol thanks for the reply,

I was able to generate an image with direct call plantuml in docker and it works.
Also the problem reproduced with metanorma in docker, let me have a look at logs for more details

**Comment by CAMOBAP** [comment]
> Any chance of getting the version of PlantUML updated in the Docker container?

Let me have a look, for now, we install plantuml from alpine's package repository and 1.2024.x available only in edge https://pkgs.alpinelinux.org/packages?name=plantuml&branch=edge&repo=&arch=&maintainer=

As a workaround you can use Dockerfile:

```
FROM metanorma/metanorma:1.9.4

RUN curl -L https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar -o plantuml.jar
```

I will work to update to update our install plantuml scripts to get more recent version

BTW maybe you can describe your findings here, which version of plantuml works for you?

**Comment by lrosenthol** [comment]
If you use the online version of PlantUML at https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 - the provided sample works just fine.

Locally, I am running `PlantUML version 1.2024.3 (Thu Feb 15 14:40:05 EST 2024)` and that also works.

**Comment by CAMOBAP** [comment]
Well, I have updated plantuml to latest (at the moment `PlantUML version 1.2024.3 (Thu Feb 15 19:40:05 UTC 2024)`) available in `metanorma/metanorma:main`, but this doesn't resolve the problem.

After looking in the deep, json getting corrupted during `asciidoctor` preprocessing, namely it becomes:

```
@startuml
allowmixing

json Template {
	"action": "com.joesphoto.filter",
	"description": "Magic Filter",
	"digitalSourceType": "link:++http://cv.iptc.org/newscodes/digitalsourcetype/compositeSynthetic"++[],
	"softwareAgent" : [{
		"name": "Joe's Photo Editor",
		"version": "2.0",
		"schema.org.SoftwareApplication.operatingSystem": "Windows 10"
	}]
}
@enduml
```

i.e. `link:++{}++[]` append to `digitalSourceType` value

### Workaround

A single workaround that was found is to preprocess link ahead i.e.:

```
"digitalSourceType": "+http://cv.iptc.org/newscodes/digitalsourcetype/compositeSynthetic+",
```

@lrosenthol will this workaround acceptable for you

---

It looks to me that we should forbid `asciidoc` 'preprocessing' in `[plantuml]` blocks?

@ronaldtse @opoudjis maybe you have an thoughts on this?

**Comment by opoudjis** [comment]
Ugh. There's always something. Yes, I guess we should, or else reorder the PlantUML and the links preprocessor. I'll make this a separate ticket.

**Comment by opoudjis** [comment]
Very impressed that you tracked this down btw, @CAMOBAP . Given how the Asciidoctor code is set up, that cannot have have been easy to...

**Comment by lrosenthol** [comment]
@CAMOBAP WOW - great find...

If I was only processing this text with Metanorma, then yes, that workaround would be fine....but my AsciiDoc "source" is output through three different processors (which is why I pushed for the conditionals as my first issue), so this workaround won't work for me.

As I can pre-process the PlantUML into images before the Metanorma phase, I am fine for now - but glad that the issue has now been located and an issue filed to track it!

**Comment by opoudjis** [comment]
Resolved issue, fix will be in next Monday's release.
