### ISSUE TITLE
Incorrect rendering of SVG images in HTML output

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma#359]
In relation to https://github.com/metanorma/iso-10303-detached-docs/pull/276

There are cases where SVG images look incorrectly rendered in HTML output. While they look correct in PDF.

Example from ISO 10303-110:

PDF (good rendering):
![issue1-pdf](https://github.com/metanorma/iso-10303-detached-docs/assets/33627611/2e3fcdc1-03e9-42e7-8ef9-b3d01f6f61f7)

HTML (bad rendering):
![issue1-html](https://github.com/metanorma/iso-10303-detached-docs/assets/33627611/408a671e-83e8-4895-89c1-0073162ac596)

**Comment by ronaldtse** [comment]
SVG rendering in the browser does not always match the intended rendering. 

Could you please help check whether the resulting SVG file in the HTML (save image as) is identical to the original (through a diff)?

**Comment by manuelfuenmayor** [comment]
@ronaldtse this is the image file directly opened from the browser:

![issue1-html-original](https://github.com/metanorma/metanorma/assets/33627611/5e18bf36-41ca-4c34-a88b-cdc983edab76)

It renders practically equal to the PDF output.

**Comment by ronaldtse** [comment]
So the problem is that Metanorma did something funny to the SVG in HTML that caused it to appear broken. 

Ping @opoudjis

**Comment by opoudjis** [comment]
I have no idea what is happening. This somehow involves the greater CSS context.

First issue: there is clipping on the image. I need to add +2 px to the height and width, compared to the viewbox: so 

````
width="616" height="569" viewbox="0 0 614 567"
````

**Comment by opoudjis** [comment]
The major issue is the presence in the same HTML of the Annex D diagrams and the Clause 4 diagrams, which somehow interfere with each other.

The main culprit is fig_d23, although fig_d28 also needs to go away for the fig-basis-flesh1 image to emerge undistorted.

All ids and references to ids in fig-basis-flesh1 are made unambiguous in the document by suffixing them with _inject_1

Some ids are suffixed in fig_d23 with _inject_27. But some are not:

````
		<clippath id="JE_inject_27">
			<path d="M772.715 2178.36h4430.01v4340.01H772.715z">
			</path>
		</clippath>
		<clippath id="JF">
			<path d="M772.715 2178.36h4430.01v4340.01H772.715z">
			</path>
		</clippath>
		<clippath id="JG">
			<path d="M772.715 2178.36h4430.01v4340.01H772.715z">
			</path>
		</clippath>
````

If not all ids are disambiguated for all SVGs in a document, then this is going to lead to collisions. The fact that all anchors up to JE are suffixed, and all anchors from JF are not (which also extends to anchor links) suggests a systematic processing constraint.

**Comment by opoudjis** [comment]
No, it's not the ids. It's that the style definitions in the two SVGs clashed:

````
.B{fill:none}.C{stroke:#000}.D{stroke-linejoin:round}.E{stroke-miterlimit:10}.F{stroke-width:5}.G{stroke-linecap:round}.H{stroke-width:3.9}.I{fill:#fff}.J{stroke-dasharray:30.0001, 30.0001}.K{stroke-width:15}
````

vs

````
.B{stroke-linejoin:round}.C{stroke-miterlimit:10}.D{fill:none}.E{stroke:#000}.F{stroke-width:5}.G{stroke-width:3.9}.H{stroke-linecap:round}.I{fill:#fff}.J{stroke-width:15}.K{stroke-dasharray:30.0001, 30.0001}
````

The fact that style definitions local to different SVG instances can clash in HTML is real:

https://stackoverflow.com/questions/51725393/svgs-override-each-others-css-style

To address this, I need to introduce disambiguating suffixes for all css styles in SVG, as I am already having to do with SVG ids.

It appears that having a lobotomy is a prerequisite to implementing SVG rendering in browsers.

**Comment by opoudjis** [comment]
This update has addressed the rendering issue. I am parsing the CSS, and presupposing that the svg/style definitions are all top-level selectors.
