### ISSUE TITLE
Standardize on capitalization in flavor module names

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#367]
Noticed that the flavor modules are inconsistently named.

```sh
$ metanorma -v
...
Metanorma::ISO 2.7.5
Metanorma::Iec 2.4.5
Metanorma::IEEE 1.2.6
Metanorma::Ietf 3.3.5
Metanorma::Generic 2.6.3
Metanorma::BIPM 2.4.5
Metanorma::CC 2.4.5
Metanorma::Csa 2.4.5
Metanorma::IHO 0.9.5
Metanorma::JIS 0.2.5
Metanorma::UN 0.12.6
Metanorma::Ogc 2.5.5
Metanorma::ITU 2.4.5
```

The Ruby convention is CamelCase.

We should change the following:
* ISO => Iso
* IEEE => Ieee
* BIPM => Bipm
* IHO => Iho
* JIS => Jis
* UN => Un
* ITU => Itu

**Comment by opoudjis** [comment]
Now becomes necessary for metaprogramming invoked for https://github.com/metanorma/metanorma/issues/416: there is inconsistency between module names for Processor and Converter
