### ISSUE TITLE
Set up thread for announcing and summarising Metanorma releases

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#370]
https://github.com/metanorma/discussions

Advertise and document that discussion thread.

Summarising each Metanorma release was one of the major suggestions Tina Lüdtke made when she worked with us.

**Comment by opoudjis** [comment]
Alert: @ghobona @gbuehler @jerstlouis @ReesePlews @taddhar @TRThurman @douglm @ronaldtse @manuelfuenmayor @anermina @kwkwan 

Please monitor https://github.com/metanorma/discussions/discussions/6 from now on. I will be posting summaries of what has changed in each release as I initiate the release process, and my colleague @CAMOBAP will be posting notices there when each release successfully results in a Docker image update. Please notify any colleagues that will find that information useful.

**Comment by ReesePlews** [comment]
@opoudjis thanks for doing that. very helpful information there! i really appreciate the work you and the team are doing!  thank you!
