### ISSUE TITLE
Allow Metanorma to adopt new format of collection.yml

### ISSUE THREAD

**Issue by kwkwan** [metanorma/metanorma#377]
Referring to https://github.com/metanorma/metanorma-cli/issues/328 and https://github.com/metanorma/metanorma/pull/372, modification will be made to allow Metanorma to adopt new format of collection.yml.

**Comment by opoudjis** [comment]
Please assign all Metanorma tickets you are working on to the Metanorma project. We need to keep track of everything going on.

**Comment by kwkwan** [comment]
Closed as completed via https://github.com/metanorma/metanorma/pull/379
