### ISSUE TITLE
Move all metanorma-associated gems to metanorma github repository

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#38]

**Comment by opoudjis** [comment]
@ronaldtse you will need to set up the repository

**Comment by strogonoff** [comment]
Are we moving towards single-repo model? Or do we keep separate repos but create a separate “metanorma” org on GitHub?

**Comment by ronaldtse** [comment]
We're going to move towards the "metanorma" org. But due to the admin effort amounted, we're going to take our time doing so...

**Comment by strogonoff** [comment]
Got it, org is a great idea IMO, was thinking about it too
