### ISSUE TITLE
Ghostscript failing to install on GHA for Mac

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#381]
https://github.com/metanorma/metanorma/actions/runs/8967952943/job/24626454106

@CAMOBAP @ronaldtse  Every fortnightly release of Metanorma, I have to deal with another piece of infrastructure falling over on GHA; and you both know that is not hyperbole, but a statement of fact. This is making a mockery of any any automated testing, and it is an abuse of my limited time. YOU MUST implement some sort of regular monitoring of GHA, running jobs every few days, so that these issues can be anticipated and remedied in advance of releases; and clearly that needs to range beyond standoc, to any gem that has non-trivial infrastructure (metanorma, isodoc). 

This is a reputational risk, and it needs to be treated as one.

**Comment by CAMOBAP** [comment]
@opoudjis Ghostscript installation fixed for macOS

Are failures on Ubuntu, Windows also related to infrastructure issues?

**Comment by opoudjis** [comment]
Yes, as you can see in 

https://github.com/metanorma/metanorma-cli/actions/runs/8972014184/job/24656740117

Windows, Ruby 3.0: 

````
27 gems installed
Run fontist update
/c/Users/runneradmin/.local/share/gem/ruby/3.0.0/bin/fontist: line 6: /c/Users/runneradmin/.local/share/gem/ruby/3.0.0/bin/ruby: No such file or directory
````

This is triggered before Windows gets to rspec.

The Ubuntu error is the Vectory issue I've just reported on https://github.com/metanorma/vectory/issues/41

**Comment by CAMOBAP** [comment]
It looks like a temporary issue, I don't see it in GHA logs anymore
