### ISSUE TITLE
URGENT: Fontist config disrupting GHA on running PDF generation

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#395]
The following repositories are having their generation of PDFs disrupted on GitHub Actions, possibly because of recent changes in metanorma configuration of Fontist options:

* https://github.com/metanorma/metanorma-iso/actions/runs/9541775374
* https://github.com/metanorma/metanorma-itu/actions/runs/9541918917/job/26295844127
* https://github.com/metanorma/metanorma-nist/actions/runs/9541951158/job/26295923881
* https://github.com/metanorma/metanorma-ogc/actions/runs/9542028572/job/26296150770
* https://github.com/metanorma/metanorma-un/actions/runs/9542042464
* https://github.com/metanorma/metanorma-iho/actions/runs/9542740285/job/26298083828
* https://github.com/metanorma/metanorma-iec/actions/runs/9542936942/job/26298624910
* https://github.com/metanorma/metanorma-bsi/actions/runs/9543177388
* https://github.com/metanorma/metanorma-jis/actions/runs/9543286393

Release of Plateau and BIPM is prevented by the failure to update these gems, so that issue may extend to them. The only Metanorma flavours not impacted are CC, CSA, Ribose, and the issue emerges around the installation of particular fonts, notably Arial.

This is preventing this fortnight's Metanorma release from proceeding.

**Comment by opoudjis** [comment]
Addressed, it was my side.

**Comment by ronaldtse** [comment]
This is no longer an issue.
