### ISSUE TITLE
Complete fixes for `no-install-fonts` issue

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#396]
In a recent iteration the `no-install-fonts` option was changed to a positive `install-fonts` option.

This caused many issues where there are legacy code that uses its logic:
* https://github.com/search?q=org%3Ametanorma+no_install_fonts&type=code

This task is to complete the fixes.

**Comment by opoudjis** [comment]
Updating, but given that CC and CSA didn't crash, this cannot be the only issue
