### ISSUE TITLE
Request for more repositories to be migrated to github.com/metanorma

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#40]
The following must move:

https://github.com/riboseinc/metanorma-sample
https://github.com/riboseinc/metanorma-unece

The following should move, because all comparable repos in their class are already there:

https://github.com/riboseinc/basicdoc-models
https://github.com/riboseinc/ietfbib
https://github.com/riboseinc/gmt-0010-2012

The following should move:

https://github.com/riboseinc/iso690render
https://github.com/riboseinc/iso690xml

I'd like to argue one more time for these to be moved:

https://github.com/riboseinc/relaton-cli
https://github.com/riboseinc/relaton-models
https://github.com/riboseinc/relaton-server-csd
https://github.com/riboseinc/relaton

**Comment by opoudjis** [comment]
Done, thank you

**Comment by opoudjis** [comment]
Actually, sorry, nistbib also needs to migrate

**Comment by ronaldtse** [comment]
All done!
