### ISSUE TITLE
Unable to turn off syntax highlighting

### ISSUE THREAD

**Issue by lrosenthol** [metanorma/metanorma#400]
The ISO Editor for our document has requested that we disable syntax highlighting in our document.  To do so, added `:source-highlighter: false` to the top of the `.adoc` file that is built.   However, it still highlights :(.

I noticed that in the command line to the java app for creating the PDF, it has `--syntax-highlight`:
```java -Xss10m -Xmx3g -Djava.awt.headless=true -Duser.home=/root -jar /usr/local/bundle/gems/mn2pdf-1.92/lib/../bin/mn2pdf.jar --xml-file "/tmp/core_foundation20240802-1-vdeykt.xml" --xsl-file "/usr/local/bundle/gems/metanorma-iso-2.7.10/lib/isodoc/iso/iso.international-standard.xsl" --pdf-file "/metanorma/_site/documents/core_foundation.pdf" --param baseassetpath="/metanorma/sources" --syntax-highlight  --font-manifest "/tmp/fontist_locations20240802-1-2trd8g.yml"
```

I am currently building via Docker. but I suspect that I will get the same results locally. 

Is there a way to resolve this or is it a bug in MN?

**Comment by lrosenthol** [comment]
In case it matters, each of my code fragments has the language specified, e.g., `[source,json]` or `[source,yaml]`

**Comment by Intelligent2013** [comment]
@lrosenthol I can't repeat this issue.

For sample adoc:
```adoc
= Source highlight test
:docnumber: 11111
:tc-docnumber: 11111
:edition: 1
:revdate: 2024-08-01
:copyright-year: 2016
:language: en
:title-main-en: Source highlight test
:doctype: international-standard
:docstage: 60
:docsubstage: 60
:library-ics: 67.060
:mn-document-class: iso
:mn-output-extensions: xml,html,doc,html_alt,pdf,rxl
:local-cache-only:

== Scope

Source sample:

[source,yaml]
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
```

PDF renders so:
![image](https://github.com/user-attachments/assets/e562a7fa-a8ac-4c02-9e6a-3cbd1e0927a1)


For sample adoc with `:source-highlighter: false`
```adoc
= Source highlight test
:docnumber: 11111
:tc-docnumber: 11111
:edition: 1
:revdate: 2024-08-01
:copyright-year: 2016
:language: en
:title-main-en: Source highlight test
:doctype: international-standard
:docstage: 60
:docsubstage: 60
:library-ics: 67.060
:mn-document-class: iso
:mn-output-extensions: xml,html,doc,html_alt,pdf,rxl
:local-cache-only:
:source-highlighter: false

== Scope

Source sample:

[source,yaml]
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
```

the PDF renders without highlighting:
![image](https://github.com/user-attachments/assets/ae8c9f07-116d-44d0-bff0-fe0fea0eb855)


Please make sure that there isn't empty line(s) between the document attributes like this:
```adoc
:mn-output-extensions: xml,html,doc,html_alt,pdf,rxl
:local-cache-only:

:source-highlighter: false

== Scope
...
```

Could you attach your source adoc small fragment?



> I noticed that in the command line to the java app for creating the PDF, it has `--syntax-highlight`:

The command line parameter `--syntax-highlight` is obsoleted and currently doesn't have any affect on PDF rendering.

**Comment by lrosenthol** [comment]
The "Please make sure that there isn't empty line(s) between the document attributes like this:" was the clue - thanks!  

I don't see that requirement/limitation mentioned anywhere in the documentation for document attributes either in Metanorma (https://www.metanorma.org/author/ref/document-attributes/) or AsciiDoc itself (https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/).   

Do you know where that is documented?

**Comment by opoudjis** [comment]
https://docs.asciidoctor.org/asciidoc/latest/document/header/

> The optional document header is a series of contiguous lines at the start of the AsciiDoc source, after skipping any empty or comment lines. If a document has a header, no content blocks are permitted above it. In other words, the document must start with a document header if it has one.

> IMPORTANT

> The document header may not contain empty lines. The first empty line the processor encounters after the document header begins marks the [end of the document header](https://docs.asciidoctor.org/asciidoc/latest/document/header/#when-does-the-document-header-end) and the start of the document body.
