### ISSUE TITLE
Use Lutaml-Model instead of Shale

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#401]
https://github.com/lutaml/lutaml-model/

**Comment by opoudjis** [comment]
I was told explicitly that this was a drop-in substitution for Shale, and that I therefore would not have to waste any time in making the transition from the existing implementation in Shale to Lutaml::Model.

That is clearly not the case, and even after working out the equivalents, the port outright fails.

I am checking in the failing PR, and assigning it to @HassanAkbar.

**Comment by ronaldtse** [comment]
> the port outright fails.

@opoudjis it's hard to answer your claim on "failures" since no details are provided.

**Comment by ronaldtse** [comment]
The PR is at #403.

**Comment by opoudjis** [comment]
> > the port outright fails.
> 
> @opoudjis it's hard to answer your claim on "failures" since no details are provided.

The failed PR, described in that comment, posted immediately after that comment, and assigned to Hassan, is all the detail I needed to provide. And I did.

**Comment by opoudjis** [comment]
My request for feedback was not actioned. Lutaml-Model is much stricter than Shale on attribute configuration.

**Comment by opoudjis** [comment]
Metanorma config files include optional prefatory and concluding text, marked up in Metanorma.

Shale allowed strings to be passed unparsed, so that I could ingest and reexport Metanorma XML unprocessed.

In my vision, that is sensible. There is no point deserialising and reserialising something that is extraneous to the current model; I should be able to just treat it as a passthrough.

@ronaldtse disagrees, and in his vision,

https://github.com/lutaml/lutaml-model/issues/57#issuecomment-2342612081

> Clearly we need to parse the content as a proper text model that checks its grammar/validity. Handling it as a string is a bad hack.

> What is the text model there though?

The text model, both for Relaton identifiers (and titles and abstracts), and in Metanorma collection config, is Metanorma. And it is not just inline content, as with what that ticket deals with: it is the blocks and clauses of Metanorma (though not at this stage its metadata).

That means that, as it stands, the only way I can get arbitrary Metanorma XML injected into a Lutaml-Model serialisation is by someone building a lutaml-model set of classes for the 7000 lines of Relax NG, 3700 lines of annotated Relax NC, contained in

https://github.com/metanorma/metanorma-model-iso/blob/main/grammars/isodoc.rnc
https://github.com/metanorma/basicdoc-models/blob/main/grammars/basicdoc.rnc
https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc
https://github.com/relaton/relaton-models/blob/main/grammars/biblio-standoc.rnc
https://github.com/metanorma/metanorma-requirements-models/blob/main/grammars/reqt.rnc

And I have no reason to think that this expectation will be relented on.

Oh, and Metanorma text can also contain MathML. Which I deliberately do NOT provide a grammar for or validate, and treat as `xs:any`, because MathML is extraneous to my concerns (and I'm not even sure the RNG validator would cope with it). And any attempt to integrate MathML XML into Lutaml-Model deserialisation should be a bridge too far, and reason to pause and think whether there is a point of doing all this for the sake of "a proper text model that checks its grammar/validity" (when Metanorma *is already doing that anyway*.)

Until an approach for dealing with arbitrary Metanorma XML in lutaml-model happens, then, I can't finish lutaml-model integration of Metanorma config, and I strongly encourage @andrew2net not to continue with relaton integration either: clearly hardcoding `<sup>` and `<sub>` as identifier attributes, as he currently does, is unacceptable, when 

. titles can contain any inline Metanorma markup, including italics, boldface, and underlines; and 
. abstracts can contain any Metanorma block as well;
. *AND* MathML can turn up anywhere.

There are three ways forward here.

* What I surmise Ronald expects is full deserialisation of any XML that may end up in a payload in the Metanorma ecosystem, whether it is Metanorma, Relaton, MathML, STS, or the completely open-ended XML allowed in metanorma-extension. I clearly think that's overkill, and indeed both unsustainable and pointless, but I'm not the boss.
* We allow the option of strings to be passed through as strings, unparsed, and do not make an unnecessary rod for our backs. Ronald appears to have already rejected this as a hack. I don't see that creating an object model of all of MathML, just to get a title up, is so much better an idea.
* There is in fact a third option, which is much more painless. Right now, arbitrary XML in a string is in fact deserialised, as ::Lutaml::Model::MappingHash. When I debug the processing of prefatory text, I get:

````
{"text"=>["\n    ", "\n  "], "clause"=>{"text"=>["\n      ", "\n      ", "\n    "], "title"=>{"text"=>"Clause"}, "p"=>{"text"=>"Welcome to our collection", "id"=>""}, "id"=>"_clause", "inline-header"=>"false", "obligation"=>"normative"}}
````

(This is a simple mapping of XML to a hash, and XML-to-JSON mappings like Goessner uncovered that it gets much more complicated very quickly if you want reversible mappings; but I'll leave that aside.)

Implementing to_xml on ::Lutaml::Model::MappingHash, and merely reserialising the XML we put in to begin with, would make all of this go away. You've clearly relented and allowed arbitrary XML to be deserialised into MappingHash; I'm requesting the inverse operation.

@ronaldtse Over to you.

**Comment by opoudjis** [comment]
Now stuck at 

* [ ] https://github.com/lutaml/lutaml-model/issues/102

**Comment by opoudjis** [comment]
Now stuck at:

https://github.com/lutaml/lutaml-model/issues/117

This has gone on for three months.
