### ISSUE TITLE
latexmath adding commas to numbers

### ISSUE THREAD

**Issue by stuartgalt** [metanorma/metanorma#406]
While looking at 10303-104 output we discovered the following source 
```
[latexmath%unnumbered]
++++
\left(
\begin{array}{cccccc}
d_{1111} & d_{1122} & d_{1133} & d_{1112} & d_{1123} & d_{1131} \\
         & d_{2222} & d_{2233} & d_{2212} & d_{2223} & d_{2231} \\
         &          & d_{3333} & d_{3312} & d_{3323} & d_{3331} \\
         &          &          & d_{1212} & d_{1223} & d_{1231} \\
         & \mbox{symmetric} & & & d_{2323} & d_{2331} \\
         &          &          &          &          & d_{3131}
\end{array}
\right)
++++
```

In the rendered PDF we get the following:
![image](https://github.com/user-attachments/assets/4500c4d6-3c69-40cc-97c4-7fe2de1c426f)

But I was actually expecting 
![image](https://github.com/user-attachments/assets/3c3f1cd5-379f-4c5d-9cfa-865e5580762e)

Is there a way to suppress the unwanted commas in the math?  Or are the commas being added in some later part of the process?

**Comment by ronaldtse** [comment]
Thanks @stuartgalt for raising this. 

I believe these commas are inserted for ISO number formatting as a number group separator, which seems incorrectly applied here. 

ISO 80000 as referenced by ISO DIR 2 dictates that numbers are to be grouped in 3 digits and use a space for separation, and a comma is used for the decimal separator. But since the 4-digit number here has no decimal portion, it seems incorrectly applied. 

Right now, there is no method to skip the number auto formatting. 

1. @suleman-uzair can you help check if this is a Plurimath issue?
2. Perhaps @suleman-uzair @opoudjis we can come up with a syntax that escapes number formatting, i.e. declaring that a number is not a number?

**Comment by opoudjis** [comment]
Number formatting in this case is being applied to the entire formula, so it would need to be suppressed for the entire formula. Since I'm passing the request for number formatting as an argument to the call to Plurimath, I'll need to come up with the syntax not to.

**Comment by ronaldtse** [comment]
Perhaps the assumption that "all numbers in a formula are numbers" is wrong? Perhaps we should require explicit declaration that numbers are numbers?

**Comment by opoudjis** [comment]
Perhaps. What I don't think we can do is differentiate numbers from non-numbers within a formula: we would need to add stuff in Latex and Asciimath that we have no business adding. There are going to be lots of science/eng cases, particularly in metrology like BIPM, where you really do want numbers to be numbers in formulae, but I agree, it likely should not be the default.

... Which means we will need to review our BIPM outputs once I implement this. OK, flag on `<stem>` to indicate numerical formatting options, taken from `number:[]`.

**Comment by stuartgalt** [comment]
Could there be a flag like 
[latexmath%numbered%noradix] 

or some more suitable name rather than radix?

**Comment by opoudjis** [comment]
What I had in mind, by default, is:

````
[stem,number-format="significant=3,decimal=','"]
++++
....
++++
````


for applying number formatting with explicit options on a formula (and `latexmath` and `asciimath` can substitute for `stem`);

````
[stem,number-format]
````

for applying the same number formatting as for numbers, inherited from the flavour (I'll need to confirm that works);

`: number-presentation-formula: significant=3,decimal=',' ` for a default to be applied to formulas; and

`:number-presentation-formula: number-presentation` to inherit the setting of `:number-presentation:` (or absent that, the flavour default).

If a document default is set for number formatting for formulas, it will need to be turned off for individual formulas; and that will be 

[stem,number-format=nil]

I'll be looking to implement that tonight. Some of these values may not get past the Asciidoctor parser, and I will need to test them out.

**Comment by opoudjis** [comment]
Inline stem macros (`stem:[]`) do not support attributes, so specifying
number formatting on inline stem macros is no currently supported, other than
through the universal application of `:number-presentation-formula:`.

That's... regrettable. If we end up having to support number formatting in inline stem macros, we will have to make up a new macro.

**Comment by stuartgalt** [comment]
This issue is not done.  When I ran this document again there is a space  between the first and remaining  three digits  

![image](https://github.com/user-attachments/assets/51a6ed41-4e23-43ee-a553-409976a85dfa)


I was not expecting  a space between the digits

**Comment by ronaldtse** [comment]
@opoudjis for you to check. Let’s not close issues until they are confirmed fixed.

**Comment by opoudjis** [comment]
Missing preemption of formatting in isodoc for mn within stem//mn; that should be straightforward.

**Comment by opoudjis** [comment]
![Screenshot 2024-09-06 at 22 22 23](https://github.com/user-attachments/assets/f7596131-ab30-4ffb-a4e7-a370cd0ef11e)

**Comment by ronaldtse** [comment]
Thank you @opoudjis ! What is the syntax change that enacted this?

**Comment by opoudjis** [comment]
No syntax change. By default, numbers will now *not* be formatted in formulae (that was an isodoc code change). If you want numbers to be formatted within formulae, you can do so either with a number-format attribute on the stem block, or through a `:number-presentation-formula:` document attribute:

https://www.metanorma.org/author/topics/inline_markup/semantic-elements/#encoding-numbers-as-formulas

**Comment by opoudjis** [comment]
@stuartgalt Please confirm it is working now

**Comment by stuartgalt** [comment]
Yes, the last run the matrix subscripts were correct.

**Comment by opoudjis** [comment]
@stuartgalt We have decided to make the behaviour of numbers inside and outside of formulas the same in https://github.com/metanorma/metanorma-standoc/issues/1001 

This means that in order to get your desired behaviour for this formula, with subscripts not notated like numbers with number formatting, you need to put `[number-format=nil]` on the formula:

````
[latexmath%unnumbered,number-format=nil]
++++
\left(
\begin{array}{cccccc}
d_{1111} & d_{1122} & d_{1133} & d_{1112} & d_{1123} & d_{1131} \\
         & d_{2222} & d_{2233} & d_{2212} & d_{2223} & d_{2231} \\
         &          & d_{3333} & d_{3312} & d_{3323} & d_{3331} \\
         &          &          & d_{1212} & d_{1223} & d_{1231} \\
         & \mbox{symmetric} & & & d_{2323} & d_{2331} \\
         &          &          &          &          & d_{3131}
\end{array}
\right)
++++
````
