### ISSUE TITLE
Write and document schema for metanorma collections

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#409]
For @strogonoff working on Firelight

**Comment by opoudjis** [comment]
@strogonoff note: https://github.com/metanorma/metanorma-model-iso/blob/main/grammars/isodoc-collection.rnc

**Comment by strogonoff** [comment]
This is an XML schema, but collections we deal with are in YAML, right? Or will I get collections in XML after fully suma-generating 10303? @ronaldtse

**Comment by strogonoff** [comment]
I see no “level”, but 10303 collections have level under manifest in attachments suma generated so far. Is it always “collection”?

**Comment by strogonoff** [comment]
Is `attachment: true` the same for every entry under `docref` with `level: attachments`?

**Comment by opoudjis** [comment]
> Is `attachment: true` the same for every entry under `docref` with `level: attachments`?

https://www.metanorma.org/author/topics/collections/configuration/

> Boolean attributes of files (attachment, sectionsplit, index) can be inherited from `entry` to all their file descendants [added in https://github.com/metanorma/metanorma/releases/tag/v2.0.0].

**Comment by opoudjis** [comment]
> I see no “level” or “docref” in the schema, and neither in isodoc nor basicdoc nor reqt, but 10303 collections have both level and docref under manifest in attachments suma generated so far.
> 
> I can infer that “docref” may mean “nested manifest”, but it’s quite confusing.

Ronald decided to rename half the tags in YAML because Ronald does not care about backward compatibility. I *do* care about backward compatibility, so we have allowed both new and old tag names in YAML, and use the new tag names in the XML.

docrefs = entry is documented in

https://www.metanorma.org/author/topics/collections/configuration/

type = level is also documented in

https://www.metanorma.org/author/topics/collections/configuration/

**Comment by opoudjis** [comment]
> This is an XML schema, but collections we deal with are in YAML, right? Or will I get collections in XML after fully suma-generating 10303? Or does it somehow map in a strict way to YAML (how?)? @ronaldtse

The manifest is in YAML. The file actually processed is in XML, and that contains everything that you see, critically including the document contents. The YAML file is translated into the XML collection file as /metanorma-collection/manifest

Until you can get someone to undelete intermediate XML file output in iso-10303, work on a more sensible collection, which has not had people go cleaning out output. I suggest, again, https://github.com/metanorma/bipm-si-brochure. See:

https://github.com/metanorma/bipm-si-brochure?tab=readme-ov-file#method-2-individual-document-generation
