### ISSUE TITLE
Windows compatibility specs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#41]
For @CAMOBAP795 (cc @opoudjis )

Since Metanorma is now useable on Windows, we want to keep it working this way.

The following gems need to incorporate Windows tests (on AppVeyor):
* metanorma-* processors
* https://github.com/metanorma/metanorma-cli
* https://github.com/metanorma/isodoc, https://github.com/metanorma/html2doc

* https://github.com/metanorma/unicode2latex
* https://github.com/metanorma/relaton-cli
* https://github.com/metanorma/relaton
* *bib (https://github.com/metanorma/unbib, https://github.com/metanorma/itubib, https://github.com/metanorma/nistbib, ...)
* https://github.com/metanorma/omml2mathml , https://github.com/metanorma/mathml2asciimath

Can you please help create AppVeyor jobs to test RSpecs of those gems? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis let me post quick summary (with focus on issues and next steps)

#### Travis & Appveyor failures
 - https://github.com/metanorma/metanorma-nist/pull/78 - highly likely broken in https://github.com/metanorma/metanorma-nist/commit/644f007f0a1703c4a4d375761cd82f666a2dbd01
 - https://github.com/metanorma/metanorma-cli/pull/31 - highly likely broken in https://github.com/metanorma/metanorma-cli/commit/9dc2cc2d83b8203277a521d413fab956c2a30739
 - https://github.com/metanorma/gbbib/pull/18 - HTTP 400 error, cannot access to http://www.std.gov.cn/search/stdPage

#### Only Appveyour
 - https://github.com/metanorma/ietfbib/pull/12
 - https://github.com/metanorma/omml2mathml/pull/2
 - https://github.com/metanorma/relaton/pull/26
 - https://github.com/metanorma/html2doc/pull/18
 - https://github.com/metanorma/itubib/pull/3 - HTTP error, could not access http://www.itu.int
 - https://github.com/metanorma/metanorma-gb/pull/95
 - https://github.com/metanorma/metanorma-ietf/pull/18

I plan go  through this list to fix issues (FIFO).

--------

#### Open questions
 - Could you please explain why in `.travis.yml` we 'fixate' bundler version like this `before_install: gem install bundler -v 2.0.1`?
 - Is it technically possible to keep all test data in VCS without need to download them (it can improve tests stability)?
 - How do you think it is make sense to test on OSX additionally?

#### Notes
 - Appveyor don't allow to run matrix in parallel for free (like travis do) and [in Oct 2018 Travis announced windows support](https://blog.travis-ci.com/2018-10-11-windows-early-release). For now out-of-box it still doesn't support good enough ruby, but let's keep eye on it

**Comment by ronaldtse** [comment]
> Could you please explain why in .travis.yml we 'fixate' bundler version like this before_install: gem install bundler -v 2.0.1?

This was purely to prevent bundler using the old version (when it first came out). It's not necessary.

> Is it technically possible to keep all test data in VCS without need to download them (it can improve tests stability)?

What do you mean as VCS?

> How do you think it is make sense to test on OSX additionally?

Makes perfect sense!


> Appveyor don't allow to run matrix in parallel for free (like travis do) and in Oct 2018 Travis announced windows support. For now out-of-box it still doesn't support good enough ruby, but let's keep eye on it

Can we use Chocolatey for Travis Windows? If so can't we build on them?

**Comment by CAMOBAP795** [comment]
@ronaldtse 

> What do you mean as VCS?

Sorry for confusion I mean git

> Can we use Chocolatey for Travis Windows? If so can't we build on them?

yep, it's preinstalled. we will just need to write own logic to install/uninstall right versions of ruby, except this I think no difficulties

**Comment by ronaldtse** [comment]
> Is it technically possible to keep all test data in git without need to download them (it can improve tests stability)?

Can you elaborate what test data needs to be downloaded?

> yep, it's preinstalled. we will just need to write own logic to install/uninstall right versions of ruby, except this I think no difficulties

Then I think we should go for it!

**Comment by CAMOBAP795** [comment]
> Can you elaborate what test data needs to be downloaded?

I will collect this info during tests fixing 

> Then I think we should go for it!

Yep, once I will fix tests, I will try it on some project and compare it with appveyor in action

**Comment by ronaldtse** [comment]
Ah -- maybe you mean the Relaton files (fetching bibliographic information from the internet). We will want to stub them in Metanorma. The fetching should be tested in the Relaton gems themselves (e.g. https://github.com/riboseinc/isobib)

**Comment by CAMOBAP795** [comment]
Let me summarize status here:
 - `metanorma/metanorma-nist` - resolved
 - `metanorma/metanorma-cli` - resolved
 - metanorma/gbbib#18 - assigned to @andrew2net
 - `metanorma/ietfbib` - fixed by disabling ruby2.3, PR ready for review https://github.com/metanorma/ietfbib/pull/14
 - `metanorma/relaton` - fixed, PR is ready for review https://github.com/metanorma/relaton/pull/28
metanorma/html2doc#18
 - `metanorma/omml2mathml` - investigation finished details here https://github.com/metanorma/omml2mathml/pull/4, PR NOT ready for review yet
 - metanorma/itubib#3 - investigation not finished yet, details https://github.com/metanorma/itubib/issues/4
 - metanorma/metanorma-gb#95 - encoding/decoding issue, investigation in progress, details here https://github.com/metanorma/metanorma-gb/issues/96
 - metanorma/metanorma-ietf#18 - investigation in progress, details here https://github.com/metanorma/metanorma-ietf/pull/18

@ronaldtse @opoudjis could you please look at https://github.com/metanorma/itubib/issues/4 , if you have some ideas please let me know

**Comment by opoudjis** [comment]
* Have referred https://github.com/metanorma/itubib/issues/4 to @andrew2net 
* Have resolved https://github.com/metanorma/html2doc/pull/20
* Am still investigating https://github.com/metanorma/metanorma-gb/issues/96

**Comment by CAMOBAP795** [comment]
Update:

Ready for review:
 - https://github.com/metanorma/gbbib/pull/20
 - https://github.com/metanorma/nistbib/pull/5
 - https://github.com/metanorma/iev/pull/9
 - https://github.com/metanorma/reverse_asciidoctor/pull/15
 - https://github.com/metanorma/metanorma-sample/pull/4
 - https://github.com/metanorma/metanorma-acme/pull/3

Left:
 - https://github.com/metanorma/metanorma-ietf - fails on appveyor & local env
 - https://github.com/metanorma/metanorma-nist - fails on both travis & appveyor & local env
 - https://github.com/metanorma/itubib/pull/3 - fails on appveyor 2.3, 2.4 problem with VCR library
 - https://github.com/metanorma/metanorma-standoc/pull/57 - fails on both travis & appveyor

😅

**Comment by CAMOBAP795** [comment]
@opoudjis After https://github.com/metanorma/metanorma-standoc/commit/f5cfc0126213e43712cbb2512b28b10ec6f8486d assertion failed `expect(html).to include('\o "1-3"')`

Maybe there is misstype? because `expect(html).to include('\o "1-2"')` works

**Comment by ronaldtse** [comment]
I think @opoudjis mentioned somewhere that this test is pending for a dependent gem update.

**Comment by CAMOBAP795** [comment]
Yep:

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis I propose to close this task because only https://github.com/metanorma/itubib/pull/6 issue is left and it's not related to appveyor integration
