### ISSUE TITLE
Introduce mn-flavor as synonym of mn-document-class

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#421]
Arises from https://github.com/metanorma/metanorma.org/pull/824

Will not remove the `mn-` prefix quite yet.

**Comment by ronaldtse** [comment]
Why not remove the prefix too?

**Comment by opoudjis** [comment]
Because unlike you, I am concerned with maintaining a stable and simple user interface. Boring I know, but also responsible. Someone has to safeguard the integrity of the interface.

And you do not get to use the argument "but nobody's using it" this time.

**Comment by ronaldtse** [comment]
Not asking you to remove the prefix but to support both with prefix and without prefix.

**Comment by opoudjis** [comment]
Fine.
