### ISSUE TITLE
Review code (document or decommission) related to Collection for identifier renaming, filename rewriting

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#423]
They were previously used here but no longer used:
https://github.com/metanorma/suma/blob/66a1ed5ba7465390e4d381b59fad870002046e30/lib/suma/processor.rb#L55-L89

Do we still need these methods?

* If yes, document them on metanorma.org
* If not, remove them.

**Comment by kwkwan** [comment]
Closed #423 as completed.
