### ISSUE TITLE
Metanorma Template Repositories requirements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#45]
A Metanorma "template repository" is one that provides a directory filled with Metanorma document templates for a certain flavor.

A template can be created in the local directory through the `metanorma new` command (https://github.com/metanorma/metanorma-cli/issues/13).

We currently have two built/functional template repositories:
* For CSD: https://github.com/metanorma/mn-templates-csd
* For OGC: https://github.com/metanorma/mn-templates-ogc

The requirements for a template repository are as follows:

* Each template repository supports only one flavor (Q: should we encode/relax this?). e.g. `https://github.com/metanorma/mn-templates-csd` means it is for `metanorma-csd`.
* `LICENSE` file: License for the templates
* `README.adoc` file: README for the templates
* `{doctype}/` is the directory for a `doctype` using `metanorma-{org}` (`doctype` as specified in the `metanorma-{org}` gem).
* `common/` is an optional directory that provides common files, such as `Gemfile`, `Makefile`, `.gitignore`, `.travis-ci.yml`, etc.

Here's how the OGC template repository looks like. 
```
├── LICENSE
├── README.adoc
├── abstract-specification -> standard
├── best-practice
│   ├── README.adoc
│   ├── UML
│   │   └── README.adoc
│   ├── abstract_tests
│   │   └── README.adoc
│   ├── code
│   │   └── README.adoc
│   ├── document.adoc
│   ├── figures
│   │   └── README.adoc
│   ├── images
│   │   └── README.adoc
│   ├── requirements
│   │   ├── README.adoc
│   │   ├── requirement.adoc
│   │   └── requirements_class.adoc
│   └── sections
│       ├── annex-a.adoc
│       ├── annex-bibliography.adoc
│       ├── annex-history.adoc
│       ├── annex-n.adoc
│       ├── clause_0_front_material.adoc
│       ├── clause_1_scope.adoc
│       ├── clause_2_conformance.adoc
│       ├── clause_3_references.adoc
│       ├── clause_4_terms_and_definitions.adoc
│       ├── clause_5_conventions.adoc
│       ├── clause_6_informative_text.adoc
│       └── clause_7_normative_text.adoc
├── common
│   ├── .gitignore
│   ├── .gitlab-ci.yml
│   ├── .travis.yml
│   ├── Gemfile
│   ├── Makefile
│   ├── Makefile.win
│   ├── appveyor.yml
    └── deploy.sh
```

In this example, `best-practice` is the `doctype`, `abstract-specification` is linked to `standard` since they use the same template.

This issue is to confirm the requirements and functionality for the template repositories.

**Comment by opoudjis** [comment]
Question 1: should we allow a template repository to support multiple flavors?

Question 2: should we move the definitions of the template repositories (the addresses of Git repos) in its own gem (e.g. metanorma-csd instead of metanorma-cli)

**Comment by ronaldtse** [comment]
We can also relax the templates a bit -- such as for NIST, we can have `nist-sp-800` vs `nist-sp-500`, which are not technically document types (the document type for both are `nist-sp`), but will be useful for those who write them since they utilize specialized attributes and document structures.

**Comment by opoudjis** [comment]
Q1: I hate the proliferation of repositories in Metanorma, but that's because I wanted the templates hosted inside the gem for each flavour. If there is going to be external repositories, then it does make more sense for each flavour to have a separate repository: they will ultimately be updated by completely different people.

Q2: I don't quite understand the question. These templates are invoked by metanorma-cli, and only metanorma-cli; making them subdirectories of metanorma-csd is not going to buy you anything.

I would only add to this that there will be flavours for which doctype is immaterial; those flavours though are covered by the common subdirectory. (That means that "common" can no longer be used as a doctype anywhere!) I'd like to think there will be flavours that do not use templates at all, but then again, noone is forcing me to use this feature.

I continue to resent the way you are forcing one document per section under sections/*. We had discussed this already, and you had agreed not to insist on it. This is forcing users to author documents a particular way, and I loathe having to write my documents that way. (I write my documents in vi and in a single-window instance of BBEdit, and you have no business forcing me to use a multi-window editor.) In fact, even if I thought these templates were a good idea, that would be reason enough for me not to use them --- or at best, to concatenate all the documents into one document immediately after initialisation.

That said, offering the option of one or another template based on this preference makes things even worse, so I find myself powerless to stop it. That's fine. I'll just avoid using templates.

"abstract-specification -> standard" Is this some sort of symbolic link? Symbolic links on remote directories are a recipe for disaster; do not do this.

Why are there README.adoc instances throughout the tree? Are they "insert text here" templates? If so, don't call them README.adoc, that's just confusing, and people are not going to rename them to something else. If they are guidance, it's actually better to leave them as *.txt files, so they are not confused with document content.

**Comment by ronaldtse** [comment]
Q1: The goal is to have the different repositories updated by different people. So we agree.

Q2:
> These templates are invoked by metanorma-cli, and only metanorma-cli; making them subdirectories of metanorma-csd is not going to buy you anything.

While the templates are invoked by `metanorma-cli`, the goal is to have `metanorma-xxx` be maintained by different people from those of `metanorma-cli`. If we put the template repository address inside `metanorma-cli`, the people who manage `metanorma-xxx` will need to make a PR to metanorma-cli in order to alter the address.

> I would only add to this that there will be flavours for which doctype is immaterial; those flavours though are covered by the common subdirectory. (That means that "common" can no longer be used as a doctype anywhere!).

Yes, but that's fine.

> I'd like to think there will be flavours that do not use templates at all, but then again, noone is forcing me to use this feature.

Technically true, but in practice everyone wants some template. It will be rare that anyone can pull the list of attributes right off their head.

> I continue to resent the way you are forcing one document per section under sections/*. We had discussed this already, and you had agreed not to insist on it. This is forcing users to author documents a particular way, and I loathe having to write my documents that way. (I write my documents in vi and in a single-window instance of BBEdit, and you have no business forcing me to use a multi-window editor.) In fact, even if I thought these templates were a good idea, that would be reason enough for me not to use them --- or at best, to concatenate all the documents into one document immediately after initialisation.

Not going to force anyone at all. `vi` supports buffers too. 

Which of the following would you prefer?
1. We could have templates that have a directory and ones that don't. 
2. "Inline" the includes / concatenate the `sections/*` into one document.

> "abstract-specification -> standard" Is this some sort of symbolic link? Symbolic links on remote directories are a recipe for disaster; do not do this.

Git should faithfully reproduce this on the local machine, did you have an issue with that?

> Why are there README.adoc instances throughout the tree? Are they "insert text here" templates? If so, don't call them README.adoc, that's just confusing, and people are not going to rename them to something else. If they are guidance, it's actually better to leave them as *.txt files, so they are not confused with document content.

It's the latter.

In the OGC templates they even differentiated them using `README.md` rather than `.adoc` to separate from the actual `.adoc` files. I'm not convinced that the play with extensions is a good idea.

There should only be one `README.adoc` for each template -- it provides guidance for the author to fill in the template. This is just like how `bundle gem foobar` produces a `README.md` for the gem author to fill in. I don't see why this is confusing.

**Comment by opoudjis** [comment]
> While the templates are invoked by metanorma-cli, the goal is to have metanorma-xxx be maintained by different people from those of metanorma-cli. If we put the template repository address inside metanorma-cli, the people who manage metanorma-xxx will need to make a PR to metanorma-cli in order to alter the address.

Fine. I thought these were going to end up separate repositories anyway.

> Which of the following would you prefer?
> 1. We could have templates that have a directory and ones that don't.
> 2. "Inline" the includes / concatenate the sections/* into one document.

At first light, I'd rather the former, for flexibility; but I can see that noone is going to want to maintain two templates in tandem that differ only in their subdirectory structure. If the latter option is easy, I'd request that.

> Git should faithfully reproduce this on the local machine, did you have an issue with that?

As symbolic links? Even so, symbolic links will end up mangled by non command-line users, who copy the entire directory on their OS somewhere else—which will break the symbolic link. I believe it is an unnecessary risk.

> README.adoc

I agree that .md vs .adoc is kind of silly, but that is responding to a need to differentiate guidance from content. I can guarantee you that people will forget to exclude those README.adoc documents from the tree when they publish, and there is too much risk that they will be included accidentally in the published document. You can prevent that risk by just using *.txt for guidance; or you can assume that users will not make mistakes.

**Comment by ronaldtse** [comment]
> 2. "Inline" the includes / concatenate the sections/* into one document.

The challenge with this is that we need to run an AsciiDoc parser over it, and that the include paths within `sections/xx.adoc` need to be adjusted to start from root. e.g. if `sections/xx.adoc` has `include:blah.adoc[]` then we need to adjust the include to `include:sections/blah.adoc`.

Maybe the former ("We could have templates that have a directory and ones that don't.") is simpler conceptually and hence the overhead will be worth it.

-----

> As symbolic links? Even so, symbolic links will end up mangled by non command-line users, who copy the entire directory on their OS somewhere else—which will break the symbolic link. I believe it is an unnecessary risk.

The symbolic links are only used in the cloning, not in the resulting "realized" template directory.

> I agree that .md vs .adoc is kind of silly, but that is responding to a need to differentiate guidance from content. I can guarantee you that people will forget to exclude those README.adoc documents from the tree when they publish, and there is too much risk that they will be included accidentally in the published document. You can prevent that risk by just using *.txt for guidance; or you can assume that users will not make mistakes.

If we separate them "compilable vs non-compilable" documents using file extensions, there is always the risk that someone will rename `README.txt` to `README.adoc` (that's me, at least), and realized the original flow stopped working.

If this is the case, I prefer having a separate config file, aka `metanorma.yml` that can guide Metanorma which documents are to be included.

**Comment by opoudjis** [comment]
> The challenge with this is that we need to run an AsciiDoc parser over it, and that the include paths within sections/xx.adoc need to be adjusted to start from root. e.g. if sections/xx.adoc has include:blah.adoc[] then we need to adjust the include to include:sections/blah.adoc.

I've already had to do this in https://github.com/metanorma/metanorma-standoc/issues/54. I think it is a misfeature to have to do this, but it is also not a legitimate objection if it's already been done.

**Comment by opoudjis** [comment]
> If we separate them "compilable vs non-compilable" documents using file extensions, there is always the risk that someone will rename README.txt to README.adoc (that's me, at least), and realized the original flow stopped working.

Far less than the risk of NOT renaming the documents, and having them accidentally included. In fact, so much less risk, I'm having trouble believing it.

> If this is the case, I prefer having a separate config file, aka metanorma.yml that can guide Metanorma which documents are to be included.

One more thing to go wrong, one more thing for users to forget to update. You either make Metanorma droolproof, and usable by people who should instead be using Word, or you make it exhaustively configurable, and ensure that experts forget to tune things. You can't be all things to all users. No, a separate config file (a manifest) is a bad idea.

**Comment by opoudjis** [comment]
I am going to do things your way, with README.adoc, unless you acknowledge the above concerns. I have explained why this is a bad idea, and a manifest is an even worse idea; but there is only so much I can take on.

Please close the ticket if you insist on README.adoc. Please assign someone a task to concatenate sections, if you think it is useful to.

**Comment by ronaldtse** [comment]
> (On concatenating sections) I've already had to do this in metanorma/metanorma-standoc#54. I think it is a misfeature to have to do this, but it is also not a legitimate objection if it's already been done.

It is probably easier to manually create separate templates rather than do the automatic flattening.

> Far less than the risk of NOT renaming the documents, and having them accidentally included. In fact, so much less risk, I'm having trouble believing it.

Well, maybe it is easier if we put `README.adoc` in `docs/README.adoc`. Then one can run `metanorma *.adoc`.

> One more thing to go wrong, one more thing for users to forget to update. You either make Metanorma droolproof, and usable by people who should instead be using Word, or you make it exhaustively configurable, and ensure that experts forget to tune things. You can't be all things to all users. No, a separate config file (a manifest) is a bad idea.

We might not need it now, but I can see the need coming soon with the Registry...

**Comment by opoudjis** [comment]
> We might not need it now, but I can see the need coming soon with the Registry...

Then keep it in the registry, and keep it away from the template, where it will do damage.

**Comment by opoudjis** [comment]
>> Far less than the risk of NOT renaming the documents, and having them accidentally included. In fact, so much less risk, I'm having trouble believing it.

> Well, maybe it is easier if we put README.adoc in docs/README.adoc. Then one can run metanorma *.adoc.

Once again, you are guaranteeing that users other than yourself are going to be confused. 

Users are going to see *.adoc, and think "I have to edit this, this is content". If you've got auxiliary help me files, for God's sake, DON'T MAKE THEM .adoc files. Leave them as .txt. You don't need the formatting.

**Comment by opoudjis** [comment]
> Please close the ticket if you insist on README.adoc. Please assign someone a task to concatenate sections, if you think it is useful to.

Since the published templates have README.adoc, I am closing this ticket. I can only advise.
