### ISSUE TITLE
FYI: Metanorma and Relaton gem dependencies

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#54]
Not... really the way to this, but I don't have your details to email you this information.

![metanorma](https://user-images.githubusercontent.com/1911039/64015971-17094980-cb69-11e9-931f-da93ce50d492.png)

# Metanorma:

No dependencies: Mathematical formatting gems

unicode2latex
omml2mathml
mathml2asciimath

Mathematical formatting dependency

mathml2asciimath -> reverse_asciidoctor

No dependencies: Word formatting

html2doc

No dependencies: Metanorma core

metanorma 

Rendering:

html2doc, metanorma -> isodoc

Metanorma base flavour:

unicode2latex, html2doc, isodoc, iev, relaton, -> metanorma-standoc

Flavours:

isodoc, metanorma-standoc -> metanorma-iso (Testing dependency: metanorma, iev)
isodoc, metanorma-iso -> metanorma-iec (Testing dependency: metanorma, iev)
isodoc, gb-agencies, metanorma-iso -> metanorma-gb  (Testing dependency: metanorma)
metanorma-standoc, isodoc -> metanorma-csand, metanorma-csd, metanorma-m3d, metanorma-rsd, metanorma-acme, metanorma-sample, metanorma-unece, metanorma-mpfd, metanorma-ogc, metanorma-itu, metanorma-ietf, metanorma-vsd
(all Testing dependency: metanorma; acme, unece, ogc, itu: Testing dependency: metanorma-cli)

CLI:

metanorma, metanorma-iso, metanorma-ietf, metanorma-gb, metanorma-csd, metanorma-csand, metanorma-m3d, metanorma-acme, metanorma-standoc, metanorma-unece, metanorma-ogc, metanorma-nist, isodoc, metanorma -> metanorma-cli

# Relaton:

No dependencies: Relaton utility gems

isoics
cnccs
gb-agencies

Base Relaton gems:

iev
isoics -> relaton-bib
relaton-bib -> relaton-iso-bib

Build on iso-bib-item: Flavour gems

relaton-iso-bib -> relaton-iec
relaton-bib -> relaton-nist, relaton-ietf, relaton-itu
relaton-iso-bib, relaton-iec -> relaton-iso
relaton-iso-bib, cnccs, gb-agencies -> relaton-gb

Build on flavour gems

relaton-gb, relaton-iso, relaton-ietf, relaton-iec, relaton-nist, relaton-itu -> relaton
relaton -> relaton-cli

**Comment by CAMOBAP795** [comment]
@opoudjis sorry for the late message, as far as I understood the idea of this task to be all on the same page, maybe you can share some update about refactoring status

Thanks

**Comment by opoudjis** [comment]
@CAMOBAP795 I never got the notification for this :(

Some of the links were redundant, and I have eliminated them. All dependencies on relaton-cli have been eliminated. Will update diagrams.

**Comment by CAMOBAP795** [comment]
@opoudjis looks like we can close this or, right?

**Comment by opoudjis** [comment]
It's an FYI ticket documenting dependencies. It does not need to be open.
