### ISSUE TITLE
Citation from/to another Metanorma document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#57]
Right now we cite like this:

```adoc
* [[[ISO9001,ISO 9001:2015]]], _AUTOFILL_

Cite: 
<<ISO9001,clause="10.1">>
```

But we will also want to cite from another Metanorma document on disk or in a registry.

Here's a proposed syntax.

```adoc
* [[[myanchor,repo:(myrepo/mydoc)]
* [[[myanchor,path:(relative-filepath)]

<<myanchor,clause="10.1">>
<<myanchor,anchor="special-anchor">>
# or
<<myanchor,#special-anchor>>
```

Something like this.

Thoughts @opoudjis ?

**Comment by opoudjis** [comment]
Not doing that. Consistency requires us to provide the document identifier in citations consistently.

**Comment by ronaldtse** [comment]
> Not doing that. Consistency requires us to provide the document identifier in citations consistently.

The document identifier can be given by that particular document's bibdata? This is just like "auto-fetching" but the auto-fetched copy is local.

**Comment by opoudjis** [comment]
The document identifier remains mandatory, that is consistent with all of metanorma, it is good practice, and I will not brook further discussion.

I will search for *.rxl and *.xml at the nominated location and ingest Relaton XML if available.

**Comment by opoudjis** [comment]
Citation URLs (provided by path citations) are suffixless in Metanorma XML; they are suffixed with doc for Word, and with html for HTML.
