### ISSUE TITLE
Create snap package for metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#63]
Snap is an updated package management system from Canonical used by Ubuntu.

A snap package should be created for Metanorma and its dependencies for an easier install (as replacement for https://github.com/metanorma/metanorma-linux-setup/blob/master/ubuntu.sh)

**Comment by CAMOBAP795** [comment]
@ronaldtse really good idea because it supports many distros https://docs.snapcraft.io/installing-snapd

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please create a separate repo metanorma-snap

**Comment by ronaldtse** [comment]
@CAMOBAP795 I think you can create it but I just did it: https://github.com/metanorma/metanorma-snap

**Comment by CAMOBAP795** [comment]
Left 
 - [ ] move metnorma to organization level https://forum.snapcraft.io/t/move-unregister-metanorma-snap/11994
 - [ ] setup CI https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci#0
 - [ ] latexml install
 - [ ] plantuml install

**Comment by CAMOBAP795** [comment]
@ronaldtse I need your help 
 - run `snapcraft enable-ci travis --refresh` on master and commit updated `.travis.yml`
 - could you please add info https://forum.snapcraft.io/t/move-unregister-metanorma-snap/11994/5 about the account where admins should move `metanorma` snap, I will confirm your comment by own comment

**Comment by ronaldtse** [comment]
@CAMOBAP795 I'm using Ubuntu but having this issue:

```sh
root@c5cae058f70a:/metanorma-snap# snapcraft enable-ci travis --refresh
Locale not set! Snapcraft will temporarily use C.UTF-8
Searching for local plugin for gem
Failed to load plugin: properties failed to load for metanorma-cli: 'source' is a required property
```

Clearly the `source` is filled in `snapcraft.yaml`...

**Comment by ronaldtse** [comment]
@CAMOBAP795 and if I remove `metanorma-cli`, I get this:

```sh
root@c5cae058f70a:/metanorma-snap# snapcraft enable-ci travis --refresh
Locale not set! Snapcraft will temporarily use C.UTF-8
Failed to load plugin: properties failed to load for puppeteer: Additional properties are not allowed ('nodejs-version' was unexpected)
```

**Comment by ronaldtse** [comment]
P.S. I'm using the docker image `ubuntu:latest`.

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you post in the forum to transfer the snap to the username "metanorma"?

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795

**Comment by CAMOBAP795** [comment]
@ronaldtse posted a message to transfer, regarding problems with `snapcraft enable-ci travis --refresh` let me doublecheck

**Comment by ronaldtse** [comment]
Thanks!

**Comment by CAMOBAP795** [comment]
Formally of this task is done, we only have problems with puppeteer, which I plan to address in the scope of https://github.com/metanorma/metanorma-snap/issues/1

@ronaldtse is this ok to close this ticket?

**Comment by ronaldtse** [comment]
Yes, indeed. Closing.
