### ISSUE TITLE
TOC click targets don't match visual targets

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/metanorma#64]
Clicking on a highlighted TOC entry does not guarantee pointing to the correct URI fragment.

See screenshots below.

## Expected behaviour

<img width="358" alt="Screenshot 2019-06-11 at 6 54 12 PM" src="https://user-images.githubusercontent.com/2649467/59266521-5e72ee80-8c7a-11e9-923d-1a8aa6b5ab35.png">

## Unexpected behaviour

<img width="358" alt="Screenshot 2019-06-11 at 6 53 57 PM" src="https://user-images.githubusercontent.com/2649467/59266526-63d03900-8c7a-11e9-8c88-27b24140d835.png">

What cannot be seen from the image is that the mouse cursor was positioned on the purple-coloured part.

**Comment by opoudjis** [comment]
Impossible for me to replicate, but there is a mangled hyperlink wrapper around the entire table of contents; I will try to get rid of it.

**Comment by ribose-jeffreylau** [comment]
Perhaps the following would illustrate the problem better:

# Sub-issue 1

I believe this is caused by the mangled `<a>` wrapper that you mentioned.

## Clicking on the outer "yellow" area would go to `#toc`

<img width="697" alt="Screenshot 2019-06-25 at 9 49 02 AM" src="https://user-images.githubusercontent.com/2649467/60103964-88beb480-972e-11e9-86d5-47bbb73f277d.png">

# Sub-issue 2

The following illustrates the mismatch between click target and visual highlight.

## Current highlight area

<img width="675" alt="Screenshot 2019-06-25 at 9 50 36 AM" src="https://user-images.githubusercontent.com/2649467/60104071-b7d52600-972e-11e9-80ca-7a8c7918fce2.png">

## Actual working click target area

<img width="765" alt="Screenshot 2019-06-25 at 9 48 41 AM" src="https://user-images.githubusercontent.com/2649467/60103978-8e1bff00-972e-11e9-82dd-3ac13dca3496.png">

# Browsers

This happens in both Firefox and Chrome.

**Comment by opoudjis** [comment]
I've been trying to work out why the wrapper is there at all; it does indeed point to the #toc itself. I can't find any reason on the code archives, so with some hesitation, I'm disabling the wrapper.

**Comment by opoudjis** [comment]
I've gotten rid of the wrapper, which I can't find justification for; I clearly copied it from the script sample page at the time, but the script seems to work fine without it. Will be reflected in next gem release.

**Comment by ribose-jeffreylau** [comment]
Thanks.  Does the fix address sub-issue 2?  The hover visual highlight of `<li>` extends beyond the area of the containing `<a>` which means it is not always the case, that when the user sees the item being highlighted, that clicking would actuate the `<a>`.

**Comment by opoudjis** [comment]
I can't reproduce the hover behaviour you're describing; I think the most useful thing to happen here is for me to send you the current HTML, and for you to tell me what you want the HTML to change to. Failing that, we can refer to @pierrefortier. 

[a.html 3.zip](https://github.com/metanorma/metanorma/files/3329608/a.html.3.zip)

**Comment by ribose-jeffreylau** [comment]
Thanks.  I made some changes to the CSS and now the click target area aligns perfectly with the hover visual highlight area:

```diff
 #toc a:hover {
+  box-shadow: none;
   color: white; }
```

```diff
- #toc li {
+ #toc li a {
    padding: 5px 10px; }
```

Note: The above most probably doesn't correspond directly to the source code --- these lines are copied from the browser's code inspector.

**Comment by ronaldtse** [comment]
Thanks guys, reopening this so it's not lost.

**Comment by opoudjis** [comment]
Making fixes, rolling out into next release (today)
