### ISSUE TITLE
Comms channel

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#74]
I've just been informed by @ronaldtse that you have been enlisted to help out with maintaining the Metanorma stack. As I've been managing the stack until now, it is important that we coordinate work, and I would request that we establish a chat channel to do so. I have access to Skype and to Slack, and I strongly request that we use Skype; from what I gather, Ribose is using Skype in general.

There is already a fair bit of documentation written up for end users, and there is also documentation for developers. The latter is meant to be up on metanorma.com, but is not accessible from the front page: go to https://www.metanorma.com/builder/

I'm happy to add to documentation, but I'd need help in identifying what the gaps are in the current documentation stack.

Once you are up to speed, we can start discussing task allocation.

**Comment by zoras** [comment]
@opoudjis could you pls share your skype / slack link?

**Comment by opoudjis** [comment]
In fact, it is opoudjis

**Comment by skalee** [comment]
Then it's Skype. I've just added @opoudjis to my contacts.
