### ISSUE TITLE
schedule writeup

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#84]
https://github.com/metanorma/metanorma/wiki/Work-schedule,-Metanorma-Relaton

**Comment by opoudjis** [comment]
Dear @ronaldtse @strogonoff @abunashir @VasBu @andrew2net @manuel489 @CAMOBAP795 @w00lf @anermina @skalee @paolobrasolin 

I have set up the foregoing page so we can keep track of what all of us are doing, to help with planning and project management. I would like for all of us to update the page every couple of weeks, with the tasks we will be doing over the next two weeks. I will be asking people what they are up to if they do not update their task list. The page also contains upcoming deadlines and plans for different Metanorma flavours, so we can plan our work accordingly.

**Comment by VasBu** [comment]
Hi Nick (all),

Thanks a lot for the mail. I don’t have any assignments planned for the next two weeks. So, you should not expect anything from my side. Anyhow, If I receive an assignment in the meanwhile, I’ll follow your instructions.

Cheers,
