### ISSUE TITLE
Synchronized installation / package releases

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#88]
Metanorma now supports a variety of execution methods:

* Docker https://github.com/metanorma/metanorma-docker/
* Single binary https://github.com/metanorma/packed-mn/
* Homebrew https://github.com/metanorma/homebrew-metanorma/
* Snap https://github.com/metanorma/metanorma-snap/
* Chocolatey https://github.com/metanorma/chocolatey-metanorma/

The important thing is to trigger releases of all these repos once we have a new release.

**Comment by boydkelly** [comment]
And at the same time, improved support for rpm distros.   The so-called linux script does not work correctly on Fedora.   There is no flatpak....   Remember there are a lot of companies and individuals who use SUSE (esp in Europe) RHEL and Fedora Workstation.  Snap is viewed as a proprietary source for many in the open source world right on par with Chocolatey and Homebrew.

**Comment by CAMOBAP** [comment]
Already done, all deliverables release started after metanorma-cli gem is published
