### ISSUE TITLE
Checklist of tasks for renaming gems

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#90]
Renaming gems is highly disruptive (WHICH IS WHY WE SHOULD NOT BE DOING IT), and several people are involved in tasks around it. (I've just discovered that metanorma-build-actions and ci-master needs to be updated with the new repository names.)

I am creating a checklist at https://github.com/metanorma/metanorma/wiki/Checklist,-renaming-gems of tasks that need to be done when a gem is renamed. Please review and edit.

**Comment by opoudjis** [comment]
I will be testing this checklist against https://github.com/metanorma/metanorma-acme/issues/17

**Comment by opoudjis** [comment]
... No response, eh?

**Comment by ronaldtse** [comment]
Made minor edits, LGTM.
