### ISSUE TITLE
Implement `metanorma setup` procedure to allow installation of necessary fonts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#95]
When the user runs setup, we should create a `~/.metanorma/fonts` directory to install all necessary fonts into. 

There should be a command `metanorma setup` (because user may upgrade metanorma gems that have additional flavors that need more fonts).

Users can install additional flavors that may require additional fonts. Running `metanorma setup` should find out requirements from these flavors and install the fonts in the proper place.

We need the user to install fonts him/herself because of font licensing for distributions -- users can download the fonts freely, but we cannot distribute them. Even on Ubuntu where there is a package to install Windows fonts, we cannot depend on it because it is in the "contrib" repository and is not enabled by default.

On Ubuntu and Mac, to install any of Microsoft's Vista fonts, we can use our script:
https://github.com/metanorma/vista-fonts-installer/

(On Windows, these Vista fonts are already provided by the system. We just need to copy them into the Metanorma fonts directory)

This means that:

1. Each flavor must provide it's own "font manifest file" to describe what fonts it requires.
1. We must have a processor for the font manifest file to know how to install each font.

Instead of making the user manually run `metanorma setup`, we can also ask the user on first run if the font directory is not setup the following:
```
Metanorma has detected that you do not have the necessary fonts installed
for PDF generation. The generated PDF will use generic fonts that may not
resemble the desired styling. Metanorma can download these files for you 
if you accept the font licensing conditions for the fonts "font-1", "font-2" .... 
If you want Metanorma to download these fonts for you and indicate your
acceptance of the font licenses, type "Yes". (Y/N?) Y
```

This is necessary for:
* https://github.com/metanorma/metanorma-docker/issues/62
* https://github.com/metanorma/homebrew-metanorma/issues/36
* https://github.com/metanorma/metanorma-linux-setup/issues/21
* https://github.com/metanorma/chocolatey-metanorma/issues/38

From @opoudjis  (https://github.com/metanorma/homebrew-metanorma/issues/36#issuecomment-593181167)
> An essential component of this work is to identify the fonts directory on the current system to be used for PDF generation. The README in mn-native-pdf is mac only, and it may be naive about assuming font locations. (I already had problems with it on my mac, because my fonts were not where it expected them to be.)

**Comment by ronaldtse** [comment]
@opoudjis has raised a good point: 

For flavors that only need Vista fonts:

1. For people on Windows, we just need to copy out the fonts automatically. This can be done using `metanorma setup`. We can run `metanorma setup` as part of the installation via Chocolatey.

2. For people on Macs that have Microsoft Office, again we just need to copy out the fonts. This can also be done using `metanorma setup`, and can be run as part of Homebrew installation.

3. For people on Linux, the Homebrew formula can help them install the fonts (by running `metanorma setup` within the formula).

This means we need to detect where system fonts are on these platforms.

For other fonts that are not provided, we should prompt the user on first run to install the fonts.

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis thanks for a detailed explanation, a couple questions from my side:

1. Maybe I can already check somewhere "font manifest file"? will it be an actual file or just a new method from  in`Metanorma::Processor`? 
I have checked `feature/xslfo` branch on `metanorma-iso` but didn't found changes related to this.
Let me know if I can get an example in some flavor 
2. Because of this task created for `metanorma/metanorma` (not for `metanorma-cli`) project, it means that core logic will be placed here, and we will just call `setup` from `metanorma-cli`, right?
3. Except for https://github.com/metanorma/vista-fonts-installer/ do we have some other scripts which can be used for other fonts?

**Comment by ronaldtse** [comment]
> 1. Maybe I can already check somewhere "font manifest file"? will it be an actual file or just a new method from inMetanorma::Processor?

We don't have this file yet, we should create one in each of the gems that have PDF functionality. Can you help do this? Maybe a YAML file is appropriate.

> 2. Because of this task created for metanorma/metanorma (not for metanorma-cli) project, it means that core logic will be placed here, and we will just call setup from metanorma-cli, right?

Yes.

> 3. Except for https://github.com/metanorma/vista-fonts-installer/ do we have some other scripts which can be used for other fonts?

Right now, we don't have other scripts. Maybe you can create a separate repo to manage font downloads and installation on different platforms?

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks for the answer, at this point, I haven't a big picture so I will start checking the code to check which fonts required by a particular processor.

I will list the result of my research here

**Comment by CAMOBAP795** [comment]
Make sense to add tags to our repositories based on https://github.com/metanorma/metanorma-build-scripts/blob/master/cimas-config/cimas.yml

To be continued
  - metanorma-acme
  - metanorma-cli
  - metanorma-csa
  - metanorma-csd
  - metanorma-docker
  - metanorma-gb
  - metanorma-iec
  - metanorma-ietf
  - metanorma-iso
  - metanorma-itu
  - metanorma-m3d
  - metanorma-mpfd
  - metanorma-nist
  - metanorma-ogc
  - metanorma-registry
  - metanorma-release
  - metanorma-rsd
  - metanorma-sample
  - metanorma-snap
  - metanorma-standoc
  - metanorma-un
  - metanorma-vsd

**Comment by ronaldtse** [comment]
I think your findings are correct. The only fonts we need to install are the Word and PDF fonts. The HTML fonts probably should utilize Google Fonts.

We should have:

Each flavor defines their own fonts (`font-requirements.yaml`)
```yaml
fonts:
  - name: Libre Baskervile
    styles:
      - name: Regular
        file: LibreBaskervill-Regular.otf
      - name: Bold
        file: LibreBaskervill-Bold.otf
  - name: Courier New

...
```

Then a CENTRAL FONTS INSTALL MAP: (maybe this should be in a separate repo)

```yaml
Libre Baskerville: 
  archive_url: https://www.fontsquirrel.com/fonts/download/libre-baskerville
  files:
    - LibreBaskerville-Regular.otf
    - LibreBaskerville-Bold.otf
    - LibreBaskerville-Italic.otf
Calibri: 
  install_mac: 
    script: |
      curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | bash

  install_linux: https://github.com/metanorma/vista-fonts-installer/
...
```

**Comment by ronaldtse** [comment]
As a first step we now have https://github.com/metanorma/source-fonts which allows easy install of Adobe Source fonts.

**Comment by ronaldtse** [comment]
Summary of steps:

1. Each metanorma-* flavor will determine a set of necessary fonts. 
2. We will then have a place to deal with "where/how to downoad the fonts". 
3. On running Metanorma with that flavor, it will ask the user whether they want to accept the licenses for those fonts (if they require any licenses), and install them
4. Those fonts will be installed inside either the System or ~/.metanorma/fonts

@abunashir do you have time to set this up?

**Comment by abunashir** [comment]
Yap, I can look into it. From the first look, I agree with Ron about having a separate library dedicated to find or download fonts and then utilize that using metanorma setup or some other interface. Here is how I would have approach this: 

* Develop a separate library(eg: `font-finder`), that will work more likely as finder or downloader for fonts(using system or internet) and then copy those fonts to the provided directory.
* Then `metanorma` will use that library, and `metanora setup` will look at it's flavor for fonts manifesto and  pass it to the `font-finder` with a download path.
* If missing fonts requires licensing agreement then `metanorma` will also prompt that for user input.

Let me know what you guys think, cc: @ronaldtse

**Comment by ronaldtse** [comment]
@abunashir exactly what I had in mind. Let's do it!

**Comment by abunashir** [comment]
Cool,  I will setup the details then.

**Comment by ronaldtse** [comment]
The "font setup" code is now located at https://github.com/fontist/fontist managed by @abunashir . 

@abunashir can you please ping this post when Fontist is functional, and start integrating with Metanorma?

**Comment by CAMOBAP795** [comment]
@abunashir is there some update on this task?

**Comment by abunashir** [comment]
@CAMOBAP795: There is, it's not complete yet but I've added a PR that will setup the required fonts. Here is a in progress PR - https://github.com/metanorma/metanorma-cli/pull/139, is this something you can use for now?

**Comment by ronaldtse** [comment]
@abunashir here's the full list -- https://github.com/metanorma/metanorma/issues/108

From that issue you can find where @opoudjis kept the font definitions, which metanorma-cli should obtain them from.

**Comment by ronaldtse** [comment]
Seems that they are:

```ruby
module Metanorma
   module UN
     def self.pdf_fonts
       ["Arial", "Arial Black", "Courier", "Times New Roman", "HanSans"]
     end
```

i.e. `Metanorma::{Flavor}.pdf_fonts`.

**Comment by opoudjis** [comment]
Not any more, I've changed them all to be `.fonts_used`, as requested.

**Comment by CAMOBAP** [comment]
I suppose because of https://github.com/metanorma/metanorma-docker/issues/62 this task isn't actual anymore. @ronaldtse can you confirm?

**Comment by opoudjis** [comment]
Btw, @CAMOBAP, it's "current" or "relevant" in English, and _actual_ is a false friend, it means фактический, not актуальный. 

Unfortunately Google Translate is unaware of that in Russian, which astounds me.

**Comment by ronaldtse** [comment]
> I suppose because of [metanorma/metanorma-docker#62](https://github.com/metanorma/metanorma-docker/issues/62) this task isn't actual anymore. @ronaldtse can you confirm?

I believe you're right, let's close this since metanorma-docker now works with the new volume. BTW, I think you might be able to "cache" the font volume in GHA while using the docker image? That would be cool.

Thanks!
