### ISSUE TITLE
Trigger docker mn build on push to master

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma#96]

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis please review attached PRs

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please add GH_USERNAME GH_ACCESS_TOKEN variables to this repo

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma/runs/487709956?check_suite_focus=true : Ubuntu build failing after latest release.

**Comment by CAMOBAP795** [comment]
@opoudjis because of https://github.com/metanorma/metanorma/issues/96#issuecomment-595218992

**Comment by ronaldtse** [comment]
@CAMOBAP795 secrets.PAT_USERNAME, secrets.PAT_TOKEN are both added. Can you confirm it works?

**Comment by ronaldtse** [comment]
Oh looks like it worked.

**Comment by ronaldtse** [comment]
@CAMOBAP795 if it's good please close this. Thanks!
